/**
 * Procedure to save/upsert storeInit data into SQLite tables:
 * 1. storeinit (rd[0])
 * 2. account (rd1)
 * 3. companyinfo (rd2[0])
 */

/**
 * Normalizes input value safely for SQLite binding
 */
function toText(val, fallback = "") {
    if (val === undefined || val === null) return fallback;
    return String(val);
}

function toInt(val, fallback = 0) {
    if (val === undefined || val === null || val === "") return fallback;
    const num = parseInt(val, 10);
    return isNaN(num) ? fallback : num;
}

function toReal(val, fallback = 0.0) {
    if (val === undefined || val === null || val === "") return fallback;
    const num = parseFloat(val);
    return isNaN(num) ? fallback : num;
}

/**
 * Saves complete storeInit data into SQLite with atomic transaction
 * @param {import('better-sqlite3').Database} db
 * @param {object} rawPayload - Raw JSON payload from API or file
 * @returns {{ success: boolean, count: { rd: number, rd1: number, rd2: number }, elapsedMs: number }}
 */
export function saveStoreInit(db, rawPayload = {}) {
    const startTime = performance.now();

    // Extract Data container if wrapped
    const dataContainer = rawPayload?.Data || rawPayload;
    const rd = Array.isArray(dataContainer?.rd) ? dataContainer.rd[0] || {} : dataContainer?.rd || {};
    const rd1 = Array.isArray(dataContainer?.rd1) ? dataContainer.rd1 : [];
    const rd2 = Array.isArray(dataContainer?.rd2) ? dataContainer.rd2[0] || {} : dataContainer?.rd2 || {};

    const transaction = db.transaction(() => {
        // ====================================================================
        // 1. Save storeinit (rd[0])
        // ====================================================================
        if (Object.keys(rd).length > 0) {
            const storeInitStmt = db.prepare(`
                INSERT INTO storeinit (
                    id, YearCode, version, ApiUrl, sv, FrontEnd_RegNo, ukey, domain, ufcc, token,
                    UploadLogicalPath, WebSiteStaticImagePath, Socket_URL, Socket_Address, Socket_Path,
                    ProCatLogbanner, favicon, companyMlogo, companylogo, companyname,
                    companyorderemail, companysupportemail, newslatter, IsB2BWebsite, PolicyApplyOnId,
                    PolicyApplyOnName, IsProductWebCustomization, IsMetalCustomization, IsDiamondCustomization,
                    IsCsCustomization, IsCeilingApply, IsMetalCustComb, IsDiamondCustComb, IsCsCustComb,
                    IsStockWebsite, IsSizeWiseDesignWt, IsEcatDesignset, IsMyaccount, IsDiscount,
                    IsPriceShow, IsPriceBreakUp, IsRoundOff, IsMetalWeight, IsDiamondWeight,
                    IsDiamondPcs, IsStoneWeight, IsStonePcs, IsGrossWeight, IsMetalTypeWithColor,
                    RoundOffval, IsColorWiseImages, IsProductListPagination, PageSize,
                    DesignImageFolBackEnd, DesignImageFol, CDNDesignImageFol, CDNDesignImageFolThumb,
                    DesignSetImageFol, AlbumImageFol, pricemanagement_pricemastersetid, pricemanagement_laboursetid,
                    SettingPriceUniqueNo, diamondpricelistname, colorstonepricelistname, PackageId,
                    PackageName, cmboDiaQCid, cmboDiaQualityColor, cmboCSQCid, cmboCSQualityColor,
                    MetalId, cmboMetalType, Country, CurrencyCodeid, CurrencyCode,
                    Currencyname, CurrencyRate, Currencysymbol, ImgTh, ImgMe,
                    ImgOr, VPath, CDNVPath, Themeno, Headerno,
                    Blockno, Footerno, IsHomeTrending, IsHomeBestSeller, IsHomeNewArrival,
                    IsHomeDesignSet, IsHomeAlbum, IsProductDetailSimilarDesign, IsProductDetailDesignSet,
                    IsGrossWtFilter, IsMetalWtFilter, IsDiamondWtFilter, IsStoneWtFilter,
                    DomainForNo, DomainFor, IsPLW, BrowserTitle, IsDesignSetInMenu,
                    DesignSetInMenu, IsVision360, Vision360URL, IsMakeToOrderBatch, CartNo,
                    IsTaxIncludePrice, FileCreateDate, CacheRebuildDate, RollOverNo,
                    IsWebMobileLoginOff, IsEcomOtpVerification, IsSolitaireWebsite, IsZeroPriceProductShow,
                    IsSignUpWithCompanyInfo, IsStaticMenu, Website_Email, IsMultiVariantCart,
                    IsRemarkOnProductDetail, IsCustomOrder, IsWhatsappNotification, updated_at
                ) VALUES (
                    1, @YearCode, @version, @ApiUrl, @sv, @FrontEnd_RegNo, @ukey, @domain, @ufcc, @token,
                    @UploadLogicalPath, @WebSiteStaticImagePath, @Socket_URL, @Socket_Address, @Socket_Path,
                    @ProCatLogbanner, @favicon, @companyMlogo, @companylogo, @companyname,
                    @companyorderemail, @companysupportemail, @newslatter, @IsB2BWebsite, @PolicyApplyOnId,
                    @PolicyApplyOnName, @IsProductWebCustomization, @IsMetalCustomization, @IsDiamondCustomization,
                    @IsCsCustomization, @IsCeilingApply, @IsMetalCustComb, @IsDiamondCustComb, @IsCsCustComb,
                    @IsStockWebsite, @IsSizeWiseDesignWt, @IsEcatDesignset, @IsMyaccount, @IsDiscount,
                    @IsPriceShow, @IsPriceBreakUp, @IsRoundOff, @IsMetalWeight, @IsDiamondWeight,
                    @IsDiamondPcs, @IsStoneWeight, @IsStonePcs, @IsGrossWeight, @IsMetalTypeWithColor,
                    @RoundOffval, @IsColorWiseImages, @IsProductListPagination, @PageSize,
                    @DesignImageFolBackEnd, @DesignImageFol, @CDNDesignImageFol, @CDNDesignImageFolThumb,
                    @DesignSetImageFol, @AlbumImageFol, @pricemanagement_pricemastersetid, @pricemanagement_laboursetid,
                    @SettingPriceUniqueNo, @diamondpricelistname, @colorstonepricelistname, @PackageId,
                    @PackageName, @cmboDiaQCid, @cmboDiaQualityColor, @cmboCSQCid, @cmboCSQualityColor,
                    @MetalId, @cmboMetalType, @Country, @CurrencyCodeid, @CurrencyCode,
                    @Currencyname, @CurrencyRate, @Currencysymbol, @ImgTh, @ImgMe,
                    @ImgOr, @VPath, @CDNVPath, @Themeno, @Headerno,
                    @Blockno, @Footerno, @IsHomeTrending, @IsHomeBestSeller, @IsHomeNewArrival,
                    @IsHomeDesignSet, @IsHomeAlbum, @IsProductDetailSimilarDesign, @IsProductDetailDesignSet,
                    @IsGrossWtFilter, @IsMetalWtFilter, @IsDiamondWtFilter, @IsStoneWtFilter,
                    @DomainForNo, @DomainFor, @IsPLW, @BrowserTitle, @IsDesignSetInMenu,
                    @DesignSetInMenu, @IsVision360, @Vision360URL, @IsMakeToOrderBatch, @CartNo,
                    @IsTaxIncludePrice, @FileCreateDate, @CacheRebuildDate, @RollOverNo,
                    @IsWebMobileLoginOff, @IsEcomOtpVerification, @IsSolitaireWebsite, @IsZeroPriceProductShow,
                    @IsSignUpWithCompanyInfo, @IsStaticMenu, @Website_Email, @IsMultiVariantCart,
                    @IsRemarkOnProductDetail, @IsCustomOrder, @IsWhatsappNotification, CURRENT_TIMESTAMP
                )
                ON CONFLICT(id) DO UPDATE SET
                    YearCode = excluded.YearCode,
                    version = excluded.version,
                    ApiUrl = excluded.ApiUrl,
                    sv = excluded.sv,
                    FrontEnd_RegNo = excluded.FrontEnd_RegNo,
                    ukey = excluded.ukey,
                    domain = excluded.domain,
                    ufcc = excluded.ufcc,
                    token = excluded.token,
                    UploadLogicalPath = excluded.UploadLogicalPath,
                    WebSiteStaticImagePath = excluded.WebSiteStaticImagePath,
                    Socket_URL = excluded.Socket_URL,
                    Socket_Address = excluded.Socket_Address,
                    Socket_Path = excluded.Socket_Path,
                    ProCatLogbanner = excluded.ProCatLogbanner,
                    favicon = excluded.favicon,
                    companyMlogo = excluded.companyMlogo,
                    companylogo = excluded.companylogo,
                    companyname = excluded.companyname,
                    companyorderemail = excluded.companyorderemail,
                    companysupportemail = excluded.companysupportemail,
                    newslatter = excluded.newslatter,
                    IsB2BWebsite = excluded.IsB2BWebsite,
                    PolicyApplyOnId = excluded.PolicyApplyOnId,
                    PolicyApplyOnName = excluded.PolicyApplyOnName,
                    IsProductWebCustomization = excluded.IsProductWebCustomization,
                    IsMetalCustomization = excluded.IsMetalCustomization,
                    IsDiamondCustomization = excluded.IsDiamondCustomization,
                    IsCsCustomization = excluded.IsCsCustomization,
                    IsCeilingApply = excluded.IsCeilingApply,
                    IsMetalCustComb = excluded.IsMetalCustComb,
                    IsDiamondCustComb = excluded.IsDiamondCustComb,
                    IsCsCustComb = excluded.IsCsCustComb,
                    IsStockWebsite = excluded.IsStockWebsite,
                    IsSizeWiseDesignWt = excluded.IsSizeWiseDesignWt,
                    IsEcatDesignset = excluded.IsEcatDesignset,
                    IsMyaccount = excluded.IsMyaccount,
                    IsDiscount = excluded.IsDiscount,
                    IsPriceShow = excluded.IsPriceShow,
                    IsPriceBreakUp = excluded.IsPriceBreakUp,
                    IsRoundOff = excluded.IsRoundOff,
                    IsMetalWeight = excluded.IsMetalWeight,
                    IsDiamondWeight = excluded.IsDiamondWeight,
                    IsDiamondPcs = excluded.IsDiamondPcs,
                    IsStoneWeight = excluded.IsStoneWeight,
                    IsStonePcs = excluded.IsStonePcs,
                    IsGrossWeight = excluded.IsGrossWeight,
                    IsMetalTypeWithColor = excluded.IsMetalTypeWithColor,
                    RoundOffval = excluded.RoundOffval,
                    IsColorWiseImages = excluded.IsColorWiseImages,
                    IsProductListPagination = excluded.IsProductListPagination,
                    PageSize = excluded.PageSize,
                    DesignImageFolBackEnd = excluded.DesignImageFolBackEnd,
                    DesignImageFol = excluded.DesignImageFol,
                    CDNDesignImageFol = excluded.CDNDesignImageFol,
                    CDNDesignImageFolThumb = excluded.CDNDesignImageFolThumb,
                    DesignSetImageFol = excluded.DesignSetImageFol,
                    AlbumImageFol = excluded.AlbumImageFol,
                    pricemanagement_pricemastersetid = excluded.pricemanagement_pricemastersetid,
                    pricemanagement_laboursetid = excluded.pricemanagement_laboursetid,
                    SettingPriceUniqueNo = excluded.SettingPriceUniqueNo,
                    diamondpricelistname = excluded.diamondpricelistname,
                    colorstonepricelistname = excluded.colorstonepricelistname,
                    PackageId = excluded.PackageId,
                    PackageName = excluded.PackageName,
                    cmboDiaQCid = excluded.cmboDiaQCid,
                    cmboDiaQualityColor = excluded.cmboDiaQualityColor,
                    cmboCSQCid = excluded.cmboCSQCid,
                    cmboCSQualityColor = excluded.cmboCSQualityColor,
                    MetalId = excluded.MetalId,
                    cmboMetalType = excluded.cmboMetalType,
                    Country = excluded.Country,
                    CurrencyCodeid = excluded.CurrencyCodeid,
                    CurrencyCode = excluded.CurrencyCode,
                    Currencyname = excluded.Currencyname,
                    CurrencyRate = excluded.CurrencyRate,
                    Currencysymbol = excluded.Currencysymbol,
                    ImgTh = excluded.ImgTh,
                    ImgMe = excluded.ImgMe,
                    ImgOr = excluded.ImgOr,
                    VPath = excluded.VPath,
                    CDNVPath = excluded.CDNVPath,
                    Themeno = excluded.Themeno,
                    Headerno = excluded.Headerno,
                    Blockno = excluded.Blockno,
                    Footerno = excluded.Footerno,
                    IsHomeTrending = excluded.IsHomeTrending,
                    IsHomeBestSeller = excluded.IsHomeBestSeller,
                    IsHomeNewArrival = excluded.IsHomeNewArrival,
                    IsHomeDesignSet = excluded.IsHomeDesignSet,
                    IsHomeAlbum = excluded.IsHomeAlbum,
                    IsProductDetailSimilarDesign = excluded.IsProductDetailSimilarDesign,
                    IsProductDetailDesignSet = excluded.IsProductDetailDesignSet,
                    IsGrossWtFilter = excluded.IsGrossWtFilter,
                    IsMetalWtFilter = excluded.IsMetalWtFilter,
                    IsDiamondWtFilter = excluded.IsDiamondWtFilter,
                    IsStoneWtFilter = excluded.IsStoneWtFilter,
                    DomainForNo = excluded.DomainForNo,
                    DomainFor = excluded.DomainFor,
                    IsPLW = excluded.IsPLW,
                    BrowserTitle = excluded.BrowserTitle,
                    IsDesignSetInMenu = excluded.IsDesignSetInMenu,
                    DesignSetInMenu = excluded.DesignSetInMenu,
                    IsVision360 = excluded.IsVision360,
                    Vision360URL = excluded.Vision360URL,
                    IsMakeToOrderBatch = excluded.IsMakeToOrderBatch,
                    CartNo = excluded.CartNo,
                    IsTaxIncludePrice = excluded.IsTaxIncludePrice,
                    FileCreateDate = excluded.FileCreateDate,
                    CacheRebuildDate = excluded.CacheRebuildDate,
                    RollOverNo = excluded.RollOverNo,
                    IsWebMobileLoginOff = excluded.IsWebMobileLoginOff,
                    IsEcomOtpVerification = excluded.IsEcomOtpVerification,
                    IsSolitaireWebsite = excluded.IsSolitaireWebsite,
                    IsZeroPriceProductShow = excluded.IsZeroPriceProductShow,
                    IsSignUpWithCompanyInfo = excluded.IsSignUpWithCompanyInfo,
                    IsStaticMenu = excluded.IsStaticMenu,
                    Website_Email = excluded.Website_Email,
                    IsMultiVariantCart = excluded.IsMultiVariantCart,
                    IsRemarkOnProductDetail = excluded.IsRemarkOnProductDetail,
                    IsCustomOrder = excluded.IsCustomOrder,
                    IsWhatsappNotification = excluded.IsWhatsappNotification,
                    updated_at = CURRENT_TIMESTAMP
            `);

            storeInitStmt.run({
                YearCode: toText(rd.YearCode),
                version: toText(rd.version),
                ApiUrl: toText(rd.ApiUrl),
                sv: toText(rd.sv),
                FrontEnd_RegNo: toText(rd.FrontEnd_RegNo),
                ukey: toText(rd.ukey),
                domain: toText(rd.domain),
                ufcc: toText(rd.ufcc),
                token: toText(rd.token),
                UploadLogicalPath: toText(rd.UploadLogicalPath),
                WebSiteStaticImagePath: toText(rd.WebSiteStaticImagePath),
                Socket_URL: toText(rd.Socket_URL),
                Socket_Address: toText(rd.Socket_Address),
                Socket_Path: toText(rd.Socket_Path),
                ProCatLogbanner: toText(rd.ProCatLogbanner),
                favicon: toText(rd.favicon),
                companyMlogo: toText(rd.companyMlogo),
                companylogo: toText(rd.companylogo),
                companyname: toText(rd.companyname),
                companyorderemail: toText(rd.companyorderemail),
                companysupportemail: toText(rd.companysupportemail),
                newslatter: toText(rd.newslatter),
                IsB2BWebsite: toInt(rd.IsB2BWebsite),
                PolicyApplyOnId: toInt(rd.PolicyApplyOnId),
                PolicyApplyOnName: toText(rd.PolicyApplyOnName),
                IsProductWebCustomization: toInt(rd.IsProductWebCustomization),
                IsMetalCustomization: toInt(rd.IsMetalCustomization),
                IsDiamondCustomization: toInt(rd.IsDiamondCustomization),
                IsCsCustomization: toInt(rd.IsCsCustomization),
                IsCeilingApply: toInt(rd.IsCeilingApply),
                IsMetalCustComb: toInt(rd.IsMetalCustComb),
                IsDiamondCustComb: toInt(rd.IsDiamondCustComb),
                IsCsCustComb: toInt(rd.IsCsCustComb),
                IsStockWebsite: toInt(rd.IsStockWebsite),
                IsSizeWiseDesignWt: toInt(rd.IsSizeWiseDesignWt),
                IsEcatDesignset: toInt(rd.IsEcatDesignset),
                IsMyaccount: toInt(rd.IsMyaccount),
                IsDiscount: toInt(rd.IsDiscount),
                IsPriceShow: toInt(rd.IsPriceShow),
                IsPriceBreakUp: toInt(rd.IsPriceBreakUp),
                IsRoundOff: toInt(rd.IsRoundOff),
                IsMetalWeight: toInt(rd.IsMetalWeight),
                IsDiamondWeight: toInt(rd.IsDiamondWeight),
                IsDiamondPcs: toInt(rd.IsDiamondPcs),
                IsStoneWeight: toInt(rd.IsStoneWeight),
                IsStonePcs: toInt(rd.IsStonePcs),
                IsGrossWeight: toInt(rd.IsGrossWeight),
                IsMetalTypeWithColor: toInt(rd.IsMetalTypeWithColor),
                RoundOffval: toReal(rd.RoundOffval),
                IsColorWiseImages: toInt(rd.IsColorWiseImages),
                IsProductListPagination: toInt(rd.IsProductListPagination),
                PageSize: toInt(rd.PageSize, 10),
                DesignImageFolBackEnd: toText(rd.DesignImageFolBackEnd),
                DesignImageFol: toText(rd.DesignImageFol),
                CDNDesignImageFol: toText(rd.CDNDesignImageFol),
                CDNDesignImageFolThumb: toText(rd.CDNDesignImageFolThumb),
                DesignSetImageFol: toText(rd.DesignSetImageFol),
                AlbumImageFol: toText(rd.AlbumImageFol),
                pricemanagement_pricemastersetid: toInt(rd.pricemanagement_pricemastersetid),
                pricemanagement_laboursetid: toInt(rd.pricemanagement_laboursetid),
                SettingPriceUniqueNo: toInt(rd.SettingPriceUniqueNo),
                diamondpricelistname: toText(rd.diamondpricelistname),
                colorstonepricelistname: toText(rd.colorstonepricelistname),
                PackageId: toInt(rd.PackageId),
                PackageName: toText(rd.PackageName),
                cmboDiaQCid: toText(rd.cmboDiaQCid),
                cmboDiaQualityColor: toText(rd.cmboDiaQualityColor),
                cmboCSQCid: toText(rd.cmboCSQCid),
                cmboCSQualityColor: toText(rd.cmboCSQualityColor),
                MetalId: toInt(rd.MetalId),
                cmboMetalType: toText(rd.cmboMetalType),
                Country: toText(rd.Country),
                CurrencyCodeid: toInt(rd.CurrencyCodeid),
                CurrencyCode: toText(rd.CurrencyCode),
                Currencyname: toText(rd.Currencyname),
                CurrencyRate: toReal(rd.CurrencyRate, 1.0),
                Currencysymbol: toText(rd.Currencysymbol),
                ImgTh: toText(rd.ImgTh),
                ImgMe: toText(rd.ImgMe),
                ImgOr: toText(rd.ImgOr),
                VPath: toText(rd.VPath),
                CDNVPath: toText(rd.CDNVPath),
                Themeno: toInt(rd.Themeno, 1),
                Headerno: toInt(rd.Headerno, 1),
                Blockno: toInt(rd.Blockno, 1),
                Footerno: toInt(rd.Footerno, 1),
                IsHomeTrending: toInt(rd.IsHomeTrending),
                IsHomeBestSeller: toInt(rd.IsHomeBestSeller),
                IsHomeNewArrival: toInt(rd.IsHomeNewArrival),
                IsHomeDesignSet: toInt(rd.IsHomeDesignSet),
                IsHomeAlbum: toInt(rd.IsHomeAlbum),
                IsProductDetailSimilarDesign: toInt(rd.IsProductDetailSimilarDesign),
                IsProductDetailDesignSet: toInt(rd.IsProductDetailDesignSet),
                IsGrossWtFilter: toInt(rd.IsGrossWtFilter),
                IsMetalWtFilter: toInt(rd.IsMetalWtFilter),
                IsDiamondWtFilter: toInt(rd.IsDiamondWtFilter),
                IsStoneWtFilter: toInt(rd.IsStoneWtFilter),
                DomainForNo: toInt(rd.DomainForNo),
                DomainFor: toText(rd.DomainFor),
                IsPLW: toInt(rd.IsPLW),
                BrowserTitle: toText(rd.BrowserTitle),
                IsDesignSetInMenu: toInt(rd.IsDesignSetInMenu),
                DesignSetInMenu: toText(rd.DesignSetInMenu),
                IsVision360: toInt(rd.IsVision360),
                Vision360URL: toText(rd.Vision360URL),
                IsMakeToOrderBatch: toInt(rd.IsMakeToOrderBatch),
                CartNo: toInt(rd.CartNo, 1),
                IsTaxIncludePrice: toInt(rd.IsTaxIncludePrice),
                FileCreateDate: toText(rd.FileCreateDate),
                CacheRebuildDate: toText(rd.CacheRebuildDate),
                RollOverNo: toInt(rd.RollOverNo),
                IsWebMobileLoginOff: toInt(rd.IsWebMobileLoginOff),
                IsEcomOtpVerification: toInt(rd.IsEcomOtpVerification),
                IsSolitaireWebsite: toInt(rd.IsSolitaireWebsite),
                IsZeroPriceProductShow: toInt(rd.IsZeroPriceProductShow),
                IsSignUpWithCompanyInfo: toInt(rd.IsSignUpWithCompanyInfo),
                IsStaticMenu: toInt(rd.IsStaticMenu),
                Website_Email: toText(rd.Website_Email),
                IsMultiVariantCart: toInt(rd.IsMultiVariantCart),
                IsRemarkOnProductDetail: toInt(rd.IsRemarkOnProductDetail),
                IsCustomOrder: toInt(rd.IsCustomOrder),
                IsWhatsappNotification: toInt(rd.IsWhatsappNotification)
            });
        }

        // ====================================================================
        // 2. Save account (rd1)
        // ====================================================================
        if (rd1.length > 0) {
            // Clear existing account entries to ensure exact sync
            db.prepare("DELETE FROM account").run();

            const accountStmt = db.prepare(`
                INSERT INTO account (pageid, submenuname, isvisible, display_order, created_at, updated_at)
                VALUES (@pageid, @submenuname, @isvisible, @display_order, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            `);

            for (let i = 0; i < rd1.length; i++) {
                const item = rd1[i];
                if (item && item.pageid) {
                    accountStmt.run({
                        pageid: toInt(item.pageid),
                        submenuname: toText(item.submenuname),
                        isvisible: toInt(item.isvisible, 1),
                        display_order: i + 1
                    });
                }
            }
        }

        // ====================================================================
        // 3. Save companyinfo (rd2[0])
        // ====================================================================
        if (Object.keys(rd2).length > 0) {
            // Build dynamic social link string
            let socialLinkStr = "";
            if (typeof rd2.SocialLinkObj === "object" && rd2.SocialLinkObj !== null) {
                socialLinkStr = JSON.stringify(rd2.SocialLinkObj);
            } else {
                socialLinkStr = toText(rd2.SocialLinkObj);
            }

            const companyStmt = db.prepare(`
                INSERT INTO companyinfo (
                    id, registrationno, projectlogolibpath, frontenddomainpath, frontendcolumnname,
                    companyname_menu, companytollfreeno, companyname_footer, isb2cstockitem,
                    isb2cstorefirstlinkactive, isdelete, deletedate, appuserid, ipaddress,
                    IsCustomizeCart, IsShowPrice, FrontEndTitle, mobiledomainpath, ipaddomainpath,
                    isShowBrand, isShowDesignWiseOrders, IsShow_Ecat_Sets, tollfreelabel,
                    IsMyPolicy, IsShowPromotionAlert, PromotionAlert_Imagename,
                    MainBanner1_Imagename, MainBanner2_Imagename, MainBanner3_Imagename, MainBanner4_Imagename,
                    MainBanner5_Imagename, MainBanner6_Imagename, MainBanner7_Imagename, MainBanner8_Imagename,
                    MainBanner9_Imagename, MainBanner10_Imagename, SubBanner1_Imagename, SubBanner2_Imagename,
                    SubBanner3_Imagename, MobileBanner1_Imagename, MobileBanner2_Imagename, MobileBanner3_Imagename,
                    MobileBanner4_Imagename, MobileBanner5_Imagename, MobileBanner6_Imagename, MobileBanner7_Imagename,
                    MobileBanner8_Imagename, MobileBanner9_Imagename, MobileBanner10_Imagename, IsB2CCustomer,
                    IsB2CCustomerMobile, paytmReturnstr, FrontEndFullName, FrontEndAddress, FrontEndCity,
                    FrontEndState, FrontEndZipCode, FrontEndContactno1, FrontEndContactno2, FrontEndEmail1,
                    FrontEndEmail2, FrontEndWebsite, IsShowPoweredBy,
                    footer_title1, footer_titlelink1, footer_title1detail1, footer_title1detail2,
                    footer_title1detail3, footer_title1detail4, footer_title1detail5, footer_title1detail6,
                    footer_title1detail7, footer_title1detaillink1, footer_title1detaillink2, footer_title1detaillink3,
                    footer_title1detaillink4, footer_title1detaillink5, footer_title1detaillink6, footer_title1detaillink7,
                    footer_title2, footer_titlelink2, footer_title2detail1, footer_title2detail2,
                    footer_title2detail3, footer_title2detail4, footer_title2detail5, footer_title2detail6,
                    footer_title2detail7, footer_title2detaillink1, footer_title2detaillink2, footer_title2detaillink3,
                    footer_title2detaillink4, footer_title2detaillink5, footer_title2detaillink6, footer_title2detaillink7,
                    footer_title3, footer_titlelink3, footer_title4, footer_titlelink4,
                    footertitle4icon_path1, footertitle4icon_path2, footertitle4icon_path3, footertitle4icon_path4,
                    footertitle4icon_path5, footertitle4icon_path6, footertitle4icon_path7, footertitle4icon_path8,
                    footertitle4icon_link1, footertitle4icon_link2, footertitle4icon_link3, footertitle4icon_link4,
                    footertitle4icon_link5, footertitle4icon_link6, footertitle4icon_link7, footertitle4icon_link8,
                    footertitle4icon_tooltip1, footertitle4icon_tooltip2, footertitle4icon_tooltip3, footertitle4icon_tooltip4,
                    footertitle4icon_tooltip5, footertitle4icon_tooltip6, footertitle4icon_tooltip7, footertitle4icon_tooltip8,
                    groupid, officeid,
                    filter_title1, filter_Updatemenu1, isfilter_title1,
                    filter_title2, filter_Updatemenu2, isfilter_title2,
                    filter_title3, filter_Updatemenu3, isfilter_title3,
                    filter_title4, filter_Updatemenu4, isfilter_title4,
                    filter_title5, filter_Updatemenu5, isfilter_title5,
                    filter_title6, filter_Updatemenu6, isfilter_title6,
                    filter_title7, filter_Updatemenu7, isfilter_title7,
                    filter_title8, filter_Updatemenu8, isfilter_title8,
                    filter_title9, filter_Updatemenu9, isfilter_title9,
                    filter_title10, filter_Updatemenu10, isfilter_title10,
                    filter_title11, filter_Updatemenu11, isfilter_title11,
                    filter_title12, filter_Updatemenu12, isfilter_title12,
                    filter_title13, filter_Updatemenu13, isfilter_title13,
                    filter_title14, filter_Updatemenu14, isfilter_title14,
                    filter_title15, filter_Updatemenu15, isfilter_title15,
                    filter_title16, filter_Updatemenu16, isfilter_title16,
                    filter_title17, filter_Updatemenu17, isfilter_title17,
                    filter_title18, filter_Updatemenu18, isfilter_title18,
                    dynamic_menu1, dynamic_menuupdate1, isdynamic_menu1,
                    dynamic_menu2, dynamic_menuupdate2, isdynamic_menu2,
                    dynamic_menu3, dynamic_menuupdate3, isdynamic_menu3,
                    dynamic_menu4, dynamic_menuupdate4, isdynamic_menu4,
                    dynamic_menu5, dynamic_menuupdate5, isdynamic_menu5,
                    dynamic_menu6, dynamic_menuupdate6, isdynamic_menu6,
                    dynamic_menu7, dynamic_menuupdate7, isdynamic_menu7,
                    dynamic_menu8, dynamic_menuupdate8, isdynamic_menu8,
                    jewellery_menu_level1, jewellery_menu_level2, jewellery_menu_level3, collection_menu_level1,
                    customize_footer,
                    footer2_title1, footer2_titlelink1, isvisiblefooter2_title1,
                    footer2_title2, footer2_titlelink2, isvisiblefooter2_title2,
                    footer2_title3, footer2_titlelink3, isvisiblefooter2_title3,
                    footer2_title4, footer2_titlelink4, isvisiblefooter2_title4,
                    footer2_title5, footer2_titlelink5, isvisiblefooter2_title5,
                    footer2_title6, footer2_titlelink6, isvisiblefooter2_title6,
                    footer2_title7, footer2_titlelink7, isvisiblefooter2_title7,
                    footer2_title8, footer2_titlelink8, isvisiblefooter2_title8,
                    footer2_title9, footer2_titlelink9, isvisiblefooter2_title9,
                    footer2_title10, footer2_titlelink10, isvisiblefooter2_title10,
                    footer2_title11, footer2_titlelink11, isvisiblefooter2_title11,
                    footer2_title12, footer2_titlelink12, isvisiblefooter2_title12,
                    footer2_title13, footer2_titlelink13, isvisiblefooter2_title13,
                    footer2_title14, footer2_titlelink14, isvisiblefooter2_title14,
                    footer2_title15, footer2_titlelink15, isvisiblefooter2_title15,
                    frontendhomepath, IsB2C, DefaultBanner_Imagename, CertificateBanner_Imagename,
                    IsMobileGenderHome, IsNewArrival, CART_SIDE_BANNER_Imagename, diamondstoredomainpath,
                    MobileHomePage_Imagename, loginpage_Imagename, IsCartPrice, bgImage,
                    parallax_Imagename, transparent_Imagename, store_domainname, uKey,
                    gdpr, IsDirectOrder, IsShowQuotation, IsB2Bwishlist, IsWhatsappShare,
                    SocialLinkObj, theme, VisitorId, updated_at
                ) VALUES (
                    1, @registrationno, @projectlogolibpath, @frontenddomainpath, @frontendcolumnname,
                    @companyname_menu, @companytollfreeno, @companyname_footer, @isb2cstockitem,
                    @isb2cstorefirstlinkactive, @isdelete, @deletedate, @appuserid, @ipaddress,
                    @IsCustomizeCart, @IsShowPrice, @FrontEndTitle, @mobiledomainpath, @ipaddomainpath,
                    @isShowBrand, @isShowDesignWiseOrders, @IsShow_Ecat_Sets, @tollfreelabel,
                    @IsMyPolicy, @IsShowPromotionAlert, @PromotionAlert_Imagename,
                    @MainBanner1_Imagename, @MainBanner2_Imagename, @MainBanner3_Imagename, @MainBanner4_Imagename,
                    @MainBanner5_Imagename, @MainBanner6_Imagename, @MainBanner7_Imagename, @MainBanner8_Imagename,
                    @MainBanner9_Imagename, @MainBanner10_Imagename, @SubBanner1_Imagename, @SubBanner2_Imagename,
                    @SubBanner3_Imagename, @MobileBanner1_Imagename, @MobileBanner2_Imagename, @MobileBanner3_Imagename,
                    @MobileBanner4_Imagename, @MobileBanner5_Imagename, @MobileBanner6_Imagename, @MobileBanner7_Imagename,
                    @MobileBanner8_Imagename, @MobileBanner9_Imagename, @MobileBanner10_Imagename, @IsB2CCustomer,
                    @IsB2CCustomerMobile, @paytmReturnstr, @FrontEndFullName, @FrontEndAddress, @FrontEndCity,
                    @FrontEndState, @FrontEndZipCode, @FrontEndContactno1, @FrontEndContactno2, @FrontEndEmail1,
                    @FrontEndEmail2, @FrontEndWebsite, @IsShowPoweredBy,
                    @footer_title1, @footer_titlelink1, @footer_title1detail1, @footer_title1detail2,
                    @footer_title1detail3, @footer_title1detail4, @footer_title1detail5, @footer_title1detail6,
                    @footer_title1detail7, @footer_title1detaillink1, @footer_title1detaillink2, @footer_title1detaillink3,
                    @footer_title1detaillink4, @footer_title1detaillink5, @footer_title1detaillink6, @footer_title1detaillink7,
                    @footer_title2, @footer_titlelink2, @footer_title2detail1, @footer_title2detail2,
                    @footer_title2detail3, @footer_title2detail4, @footer_title2detail5, @footer_title2detail6,
                    @footer_title2detail7, @footer_title2detaillink1, @footer_title2detaillink2, @footer_title2detaillink3,
                    @footer_title2detaillink4, @footer_title2detaillink5, @footer_title2detaillink6, @footer_title2detaillink7,
                    @footer_title3, @footer_titlelink3, @footer_title4, @footer_titlelink4,
                    @footertitle4icon_path1, @footertitle4icon_path2, @footertitle4icon_path3, @footertitle4icon_path4,
                    @footertitle4icon_path5, @footertitle4icon_path6, @footertitle4icon_path7, @footertitle4icon_path8,
                    @footertitle4icon_link1, @footertitle4icon_link2, @footertitle4icon_link3, @footertitle4icon_link4,
                    @footertitle4icon_link5, @footertitle4icon_link6, @footertitle4icon_link7, @footertitle4icon_link8,
                    @footertitle4icon_tooltip1, @footertitle4icon_tooltip2, @footertitle4icon_tooltip3, @footertitle4icon_tooltip4,
                    @footertitle4icon_tooltip5, @footertitle4icon_tooltip6, @footertitle4icon_tooltip7, @footertitle4icon_tooltip8,
                    @groupid, @officeid,
                    @filter_title1, @filter_Updatemenu1, @isfilter_title1,
                    @filter_title2, @filter_Updatemenu2, @isfilter_title2,
                    @filter_title3, @filter_Updatemenu3, @isfilter_title3,
                    @filter_title4, @filter_Updatemenu4, @isfilter_title4,
                    @filter_title5, @filter_Updatemenu5, @isfilter_title5,
                    @filter_title6, @filter_Updatemenu6, @isfilter_title6,
                    @filter_title7, @filter_Updatemenu7, @isfilter_title7,
                    @filter_title8, @filter_Updatemenu8, @isfilter_title8,
                    @filter_title9, @filter_Updatemenu9, @isfilter_title9,
                    @filter_title10, @filter_Updatemenu10, @isfilter_title10,
                    @filter_title11, @filter_Updatemenu11, @isfilter_title11,
                    @filter_title12, @filter_Updatemenu12, @isfilter_title12,
                    @filter_title13, @filter_Updatemenu13, @isfilter_title13,
                    @filter_title14, @filter_Updatemenu14, @isfilter_title14,
                    @filter_title15, @filter_Updatemenu15, @isfilter_title15,
                    @filter_title16, @filter_Updatemenu16, @isfilter_title16,
                    @filter_title17, @filter_Updatemenu17, @isfilter_title17,
                    @filter_title18, @filter_Updatemenu18, @isfilter_title18,
                    @dynamic_menu1, @dynamic_menuupdate1, @isdynamic_menu1,
                    @dynamic_menu2, @dynamic_menuupdate2, @isdynamic_menu2,
                    @dynamic_menu3, @dynamic_menuupdate3, @isdynamic_menu3,
                    @dynamic_menu4, @dynamic_menuupdate4, @isdynamic_menu4,
                    @dynamic_menu5, @dynamic_menuupdate5, @isdynamic_menu5,
                    @dynamic_menu6, @dynamic_menuupdate6, @isdynamic_menu6,
                    @dynamic_menu7, @dynamic_menuupdate7, @isdynamic_menu7,
                    @dynamic_menu8, @dynamic_menuupdate8, @isdynamic_menu8,
                    @jewellery_menu_level1, @jewellery_menu_level2, @jewellery_menu_level3, @collection_menu_level1,
                    @customize_footer,
                    @footer2_title1, @footer2_titlelink1, @isvisiblefooter2_title1,
                    @footer2_title2, @footer2_titlelink2, @isvisiblefooter2_title2,
                    @footer2_title3, @footer2_titlelink3, @isvisiblefooter2_title3,
                    @footer2_title4, @footer2_titlelink4, @isvisiblefooter2_title4,
                    @footer2_title5, @footer2_titlelink5, @isvisiblefooter2_title5,
                    @footer2_title6, @footer2_titlelink6, @isvisiblefooter2_title6,
                    @footer2_title7, @footer2_titlelink7, @isvisiblefooter2_title7,
                    @footer2_title8, @footer2_titlelink8, @isvisiblefooter2_title8,
                    @footer2_title9, @footer2_titlelink9, @isvisiblefooter2_title9,
                    @footer2_title10, @footer2_titlelink10, @isvisiblefooter2_title10,
                    @footer2_title11, @footer2_titlelink11, @isvisiblefooter2_title11,
                    @footer2_title12, @footer2_titlelink12, @isvisiblefooter2_title12,
                    @footer2_title13, @footer2_titlelink13, @isvisiblefooter2_title13,
                    @footer2_title14, @footer2_titlelink14, @isvisiblefooter2_title14,
                    @footer2_title15, @footer2_titlelink15, @isvisiblefooter2_title15,
                    @frontendhomepath, @IsB2C, @DefaultBanner_Imagename, @CertificateBanner_Imagename,
                    @IsMobileGenderHome, @IsNewArrival, @CART_SIDE_BANNER_Imagename, @diamondstoredomainpath,
                    @MobileHomePage_Imagename, @loginpage_Imagename, @IsCartPrice, @bgImage,
                    @parallax_Imagename, @transparent_Imagename, @store_domainname, @uKey,
                    @gdpr, @IsDirectOrder, @IsShowQuotation, @IsB2Bwishlist, @IsWhatsappShare,
                    @SocialLinkObj, @theme, @VisitorId, CURRENT_TIMESTAMP
                )
                ON CONFLICT(id) DO UPDATE SET
                    registrationno = excluded.registrationno,
                    projectlogolibpath = excluded.projectlogolibpath,
                    frontenddomainpath = excluded.frontenddomainpath,
                    frontendcolumnname = excluded.frontendcolumnname,
                    companyname_menu = excluded.companyname_menu,
                    companytollfreeno = excluded.companytollfreeno,
                    companyname_footer = excluded.companyname_footer,
                    isb2cstockitem = excluded.isb2cstockitem,
                    isb2cstorefirstlinkactive = excluded.isb2cstorefirstlinkactive,
                    isdelete = excluded.isdelete,
                    deletedate = excluded.deletedate,
                    appuserid = excluded.appuserid,
                    ipaddress = excluded.ipaddress,
                    IsCustomizeCart = excluded.IsCustomizeCart,
                    IsShowPrice = excluded.IsShowPrice,
                    FrontEndTitle = excluded.FrontEndTitle,
                    mobiledomainpath = excluded.mobiledomainpath,
                    ipaddomainpath = excluded.ipaddomainpath,
                    isShowBrand = excluded.isShowBrand,
                    isShowDesignWiseOrders = excluded.isShowDesignWiseOrders,
                    IsShow_Ecat_Sets = excluded.IsShow_Ecat_Sets,
                    tollfreelabel = excluded.tollfreelabel,
                    IsMyPolicy = excluded.IsMyPolicy,
                    IsShowPromotionAlert = excluded.IsShowPromotionAlert,
                    PromotionAlert_Imagename = excluded.PromotionAlert_Imagename,
                    MainBanner1_Imagename = excluded.MainBanner1_Imagename,
                    MainBanner2_Imagename = excluded.MainBanner2_Imagename,
                    MainBanner3_Imagename = excluded.MainBanner3_Imagename,
                    MainBanner4_Imagename = excluded.MainBanner4_Imagename,
                    MainBanner5_Imagename = excluded.MainBanner5_Imagename,
                    MainBanner6_Imagename = excluded.MainBanner6_Imagename,
                    MainBanner7_Imagename = excluded.MainBanner7_Imagename,
                    MainBanner8_Imagename = excluded.MainBanner8_Imagename,
                    MainBanner9_Imagename = excluded.MainBanner9_Imagename,
                    MainBanner10_Imagename = excluded.MainBanner10_Imagename,
                    SubBanner1_Imagename = excluded.SubBanner1_Imagename,
                    SubBanner2_Imagename = excluded.SubBanner2_Imagename,
                    SubBanner3_Imagename = excluded.SubBanner3_Imagename,
                    MobileBanner1_Imagename = excluded.MobileBanner1_Imagename,
                    MobileBanner2_Imagename = excluded.MobileBanner2_Imagename,
                    MobileBanner3_Imagename = excluded.MobileBanner3_Imagename,
                    MobileBanner4_Imagename = excluded.MobileBanner4_Imagename,
                    MobileBanner5_Imagename = excluded.MobileBanner5_Imagename,
                    MobileBanner6_Imagename = excluded.MobileBanner6_Imagename,
                    MobileBanner7_Imagename = excluded.MobileBanner7_Imagename,
                    MobileBanner8_Imagename = excluded.MobileBanner8_Imagename,
                    MobileBanner9_Imagename = excluded.MobileBanner9_Imagename,
                    MobileBanner10_Imagename = excluded.MobileBanner10_Imagename,
                    IsB2CCustomer = excluded.IsB2CCustomer,
                    IsB2CCustomerMobile = excluded.IsB2CCustomerMobile,
                    paytmReturnstr = excluded.paytmReturnstr,
                    FrontEndFullName = excluded.FrontEndFullName,
                    FrontEndAddress = excluded.FrontEndAddress,
                    FrontEndCity = excluded.FrontEndCity,
                    FrontEndState = excluded.FrontEndState,
                    FrontEndZipCode = excluded.FrontEndZipCode,
                    FrontEndContactno1 = excluded.FrontEndContactno1,
                    FrontEndContactno2 = excluded.FrontEndContactno2,
                    FrontEndEmail1 = excluded.FrontEndEmail1,
                    FrontEndEmail2 = excluded.FrontEndEmail2,
                    FrontEndWebsite = excluded.FrontEndWebsite,
                    IsShowPoweredBy = excluded.IsShowPoweredBy,
                    footer_title1 = excluded.footer_title1,
                    footer_titlelink1 = excluded.footer_titlelink1,
                    footer_title1detail1 = excluded.footer_title1detail1,
                    footer_title1detail2 = excluded.footer_title1detail2,
                    footer_title1detail3 = excluded.footer_title1detail3,
                    footer_title1detail4 = excluded.footer_title1detail4,
                    footer_title1detail5 = excluded.footer_title1detail5,
                    footer_title1detail6 = excluded.footer_title1detail6,
                    footer_title1detail7 = excluded.footer_title1detail7,
                    footer_title1detaillink1 = excluded.footer_title1detaillink1,
                    footer_title1detaillink2 = excluded.footer_title1detaillink2,
                    footer_title1detaillink3 = excluded.footer_title1detaillink3,
                    footer_title1detaillink4 = excluded.footer_title1detaillink4,
                    footer_title1detaillink5 = excluded.footer_title1detaillink5,
                    footer_title1detaillink6 = excluded.footer_title1detaillink6,
                    footer_title1detaillink7 = excluded.footer_title1detaillink7,
                    footer_title2 = excluded.footer_title2,
                    footer_titlelink2 = excluded.footer_titlelink2,
                    footer_title2detail1 = excluded.footer_title2detail1,
                    footer_title2detail2 = excluded.footer_title2detail2,
                    footer_title2detail3 = excluded.footer_title2detail3,
                    footer_title2detail4 = excluded.footer_title2detail4,
                    footer_title2detail5 = excluded.footer_title2detail5,
                    footer_title2detail6 = excluded.footer_title2detail6,
                    footer_title2detail7 = excluded.footer_title2detail7,
                    footer_title2detaillink1 = excluded.footer_title2detaillink1,
                    footer_title2detaillink2 = excluded.footer_title2detaillink2,
                    footer_title2detaillink3 = excluded.footer_title2detaillink3,
                    footer_title2detaillink4 = excluded.footer_title2detaillink4,
                    footer_title2detaillink5 = excluded.footer_title2detaillink5,
                    footer_title2detaillink6 = excluded.footer_title2detaillink6,
                    footer_title2detaillink7 = excluded.footer_title2detaillink7,
                    footer_title3 = excluded.footer_title3,
                    footer_titlelink3 = excluded.footer_titlelink3,
                    footer_title4 = excluded.footer_title4,
                    footer_titlelink4 = excluded.footer_titlelink4,
                    footertitle4icon_path1 = excluded.footertitle4icon_path1,
                    footertitle4icon_path2 = excluded.footertitle4icon_path2,
                    footertitle4icon_path3 = excluded.footertitle4icon_path3,
                    footertitle4icon_path4 = excluded.footertitle4icon_path4,
                    footertitle4icon_path5 = excluded.footertitle4icon_path5,
                    footertitle4icon_path6 = excluded.footertitle4icon_path6,
                    footertitle4icon_path7 = excluded.footertitle4icon_path7,
                    footertitle4icon_path8 = excluded.footertitle4icon_path8,
                    footertitle4icon_link1 = excluded.footertitle4icon_link1,
                    footertitle4icon_link2 = excluded.footertitle4icon_link2,
                    footertitle4icon_link3 = excluded.footertitle4icon_link3,
                    footertitle4icon_link4 = excluded.footertitle4icon_link4,
                    footertitle4icon_link5 = excluded.footertitle4icon_link5,
                    footertitle4icon_link6 = excluded.footertitle4icon_link6,
                    footertitle4icon_link7 = excluded.footertitle4icon_link7,
                    footertitle4icon_link8 = excluded.footertitle4icon_link8,
                    footertitle4icon_tooltip1 = excluded.footertitle4icon_tooltip1,
                    footertitle4icon_tooltip2 = excluded.footertitle4icon_tooltip2,
                    footertitle4icon_tooltip3 = excluded.footertitle4icon_tooltip3,
                    footertitle4icon_tooltip4 = excluded.footertitle4icon_tooltip4,
                    footertitle4icon_tooltip5 = excluded.footertitle4icon_tooltip5,
                    footertitle4icon_tooltip6 = excluded.footertitle4icon_tooltip6,
                    footertitle4icon_tooltip7 = excluded.footertitle4icon_tooltip7,
                    footertitle4icon_tooltip8 = excluded.footertitle4icon_tooltip8,
                    groupid = excluded.groupid,
                    officeid = excluded.officeid,
                    filter_title1 = excluded.filter_title1,
                    filter_Updatemenu1 = excluded.filter_Updatemenu1,
                    isfilter_title1 = excluded.isfilter_title1,
                    filter_title2 = excluded.filter_title2,
                    filter_Updatemenu2 = excluded.filter_Updatemenu2,
                    isfilter_title2 = excluded.isfilter_title2,
                    filter_title3 = excluded.filter_title3,
                    filter_Updatemenu3 = excluded.filter_Updatemenu3,
                    isfilter_title3 = excluded.isfilter_title3,
                    filter_title4 = excluded.filter_title4,
                    filter_Updatemenu4 = excluded.filter_Updatemenu4,
                    isfilter_title4 = excluded.isfilter_title4,
                    filter_title5 = excluded.filter_title5,
                    filter_Updatemenu5 = excluded.filter_Updatemenu5,
                    isfilter_title5 = excluded.isfilter_title5,
                    filter_title6 = excluded.filter_title6,
                    filter_Updatemenu6 = excluded.filter_Updatemenu6,
                    isfilter_title6 = excluded.isfilter_title6,
                    filter_title7 = excluded.filter_title7,
                    filter_Updatemenu7 = excluded.filter_Updatemenu7,
                    isfilter_title7 = excluded.isfilter_title7,
                    filter_title8 = excluded.filter_title8,
                    filter_Updatemenu8 = excluded.filter_Updatemenu8,
                    isfilter_title8 = excluded.isfilter_title8,
                    filter_title9 = excluded.filter_title9,
                    filter_Updatemenu9 = excluded.filter_Updatemenu9,
                    isfilter_title9 = excluded.isfilter_title9,
                    filter_title10 = excluded.filter_title10,
                    filter_Updatemenu10 = excluded.filter_Updatemenu10,
                    isfilter_title10 = excluded.isfilter_title10,
                    filter_title11 = excluded.filter_title11,
                    filter_Updatemenu11 = excluded.filter_Updatemenu11,
                    isfilter_title11 = excluded.isfilter_title11,
                    filter_title12 = excluded.filter_title12,
                    filter_Updatemenu12 = excluded.filter_Updatemenu12,
                    isfilter_title12 = excluded.isfilter_title12,
                    filter_title13 = excluded.filter_title13,
                    filter_Updatemenu13 = excluded.filter_Updatemenu13,
                    isfilter_title13 = excluded.isfilter_title13,
                    filter_title14 = excluded.filter_title14,
                    filter_Updatemenu14 = excluded.filter_Updatemenu14,
                    isfilter_title14 = excluded.isfilter_title14,
                    filter_title15 = excluded.filter_title15,
                    filter_Updatemenu15 = excluded.filter_Updatemenu15,
                    isfilter_title15 = excluded.isfilter_title15,
                    filter_title16 = excluded.filter_title16,
                    filter_Updatemenu16 = excluded.filter_Updatemenu16,
                    isfilter_title16 = excluded.isfilter_title16,
                    filter_title17 = excluded.filter_title17,
                    filter_Updatemenu17 = excluded.filter_Updatemenu17,
                    isfilter_title17 = excluded.isfilter_title17,
                    filter_title18 = excluded.filter_title18,
                    filter_Updatemenu18 = excluded.filter_Updatemenu18,
                    isfilter_title18 = excluded.isfilter_title18,
                    dynamic_menu1 = excluded.dynamic_menu1,
                    dynamic_menuupdate1 = excluded.dynamic_menuupdate1,
                    isdynamic_menu1 = excluded.isdynamic_menu1,
                    dynamic_menu2 = excluded.dynamic_menu2,
                    dynamic_menuupdate2 = excluded.dynamic_menuupdate2,
                    isdynamic_menu2 = excluded.isdynamic_menu2,
                    dynamic_menu3 = excluded.dynamic_menu3,
                    dynamic_menuupdate3 = excluded.dynamic_menuupdate3,
                    isdynamic_menu3 = excluded.isdynamic_menu3,
                    dynamic_menu4 = excluded.dynamic_menu4,
                    dynamic_menuupdate4 = excluded.dynamic_menuupdate4,
                    isdynamic_menu4 = excluded.isdynamic_menu4,
                    dynamic_menu5 = excluded.dynamic_menu5,
                    dynamic_menuupdate5 = excluded.dynamic_menuupdate5,
                    isdynamic_menu5 = excluded.isdynamic_menu5,
                    dynamic_menu6 = excluded.dynamic_menu6,
                    dynamic_menuupdate6 = excluded.dynamic_menuupdate6,
                    isdynamic_menu6 = excluded.isdynamic_menu6,
                    dynamic_menu7 = excluded.dynamic_menu7,
                    dynamic_menuupdate7 = excluded.dynamic_menuupdate7,
                    isdynamic_menu7 = excluded.isdynamic_menu7,
                    dynamic_menu8 = excluded.dynamic_menu8,
                    dynamic_menuupdate8 = excluded.dynamic_menuupdate8,
                    isdynamic_menu8 = excluded.isdynamic_menu8,
                    jewellery_menu_level1 = excluded.jewellery_menu_level1,
                    jewellery_menu_level2 = excluded.jewellery_menu_level2,
                    jewellery_menu_level3 = excluded.jewellery_menu_level3,
                    collection_menu_level1 = excluded.collection_menu_level1,
                    customize_footer = excluded.customize_footer,
                    footer2_title1 = excluded.footer2_title1,
                    footer2_titlelink1 = excluded.footer2_titlelink1,
                    isvisiblefooter2_title1 = excluded.isvisiblefooter2_title1,
                    footer2_title2 = excluded.footer2_title2,
                    footer2_titlelink2 = excluded.footer2_titlelink2,
                    isvisiblefooter2_title2 = excluded.isvisiblefooter2_title2,
                    footer2_title3 = excluded.footer2_title3,
                    footer2_titlelink3 = excluded.footer2_titlelink3,
                    isvisiblefooter2_title3 = excluded.isvisiblefooter2_title3,
                    footer2_title4 = excluded.footer2_title4,
                    footer2_titlelink4 = excluded.footer2_titlelink4,
                    isvisiblefooter2_title4 = excluded.isvisiblefooter2_title4,
                    footer2_title5 = excluded.footer2_title5,
                    footer2_titlelink5 = excluded.footer2_titlelink5,
                    isvisiblefooter2_title5 = excluded.isvisiblefooter2_title5,
                    footer2_title6 = excluded.footer2_title6,
                    footer2_titlelink6 = excluded.footer2_titlelink6,
                    isvisiblefooter2_title6 = excluded.isvisiblefooter2_title6,
                    footer2_title7 = excluded.footer2_title7,
                    footer2_titlelink7 = excluded.footer2_titlelink7,
                    isvisiblefooter2_title7 = excluded.isvisiblefooter2_title7,
                    footer2_title8 = excluded.footer2_title8,
                    footer2_titlelink8 = excluded.footer2_titlelink8,
                    isvisiblefooter2_title8 = excluded.isvisiblefooter2_title8,
                    footer2_title9 = excluded.footer2_title9,
                    footer2_titlelink9 = excluded.footer2_titlelink9,
                    isvisiblefooter2_title9 = excluded.isvisiblefooter2_title9,
                    footer2_title10 = excluded.footer2_title10,
                    footer2_titlelink10 = excluded.footer2_titlelink10,
                    isvisiblefooter2_title10 = excluded.isvisiblefooter2_title10,
                    footer2_title11 = excluded.footer2_title11,
                    footer2_titlelink11 = excluded.footer2_titlelink11,
                    isvisiblefooter2_title11 = excluded.isvisiblefooter2_title11,
                    footer2_title12 = excluded.footer2_title12,
                    footer2_titlelink12 = excluded.footer2_titlelink12,
                    isvisiblefooter2_title12 = excluded.isvisiblefooter2_title12,
                    footer2_title13 = excluded.footer2_title13,
                    footer2_titlelink13 = excluded.footer2_titlelink13,
                    isvisiblefooter2_title13 = excluded.isvisiblefooter2_title13,
                    footer2_title14 = excluded.footer2_title14,
                    footer2_titlelink14 = excluded.footer2_titlelink14,
                    isvisiblefooter2_title14 = excluded.isvisiblefooter2_title14,
                    footer2_title15 = excluded.footer2_title15,
                    footer2_titlelink15 = excluded.footer2_titlelink15,
                    isvisiblefooter2_title15 = excluded.isvisiblefooter2_title15,
                    frontendhomepath = excluded.frontendhomepath,
                    IsB2C = excluded.IsB2C,
                    DefaultBanner_Imagename = excluded.DefaultBanner_Imagename,
                    CertificateBanner_Imagename = excluded.CertificateBanner_Imagename,
                    IsMobileGenderHome = excluded.IsMobileGenderHome,
                    IsNewArrival = excluded.IsNewArrival,
                    CART_SIDE_BANNER_Imagename = excluded.CART_SIDE_BANNER_Imagename,
                    diamondstoredomainpath = excluded.diamondstoredomainpath,
                    MobileHomePage_Imagename = excluded.MobileHomePage_Imagename,
                    loginpage_Imagename = excluded.loginpage_Imagename,
                    IsCartPrice = excluded.IsCartPrice,
                    bgImage = excluded.bgImage,
                    parallax_Imagename = excluded.parallax_Imagename,
                    transparent_Imagename = excluded.transparent_Imagename,
                    store_domainname = excluded.store_domainname,
                    uKey = excluded.uKey,
                    gdpr = excluded.gdpr,
                    IsDirectOrder = excluded.IsDirectOrder,
                    IsShowQuotation = excluded.IsShowQuotation,
                    IsB2Bwishlist = excluded.IsB2Bwishlist,
                    IsWhatsappShare = excluded.IsWhatsappShare,
                    SocialLinkObj = excluded.SocialLinkObj,
                    theme = excluded.theme,
                    VisitorId = excluded.VisitorId,
                    updated_at = CURRENT_TIMESTAMP
            `);

            companyStmt.run({
                registrationno: toText(rd2.registrationno),
                projectlogolibpath: toText(rd2.projectlogolibpath),
                frontenddomainpath: toText(rd2.frontenddomainpath),
                frontendcolumnname: toText(rd2.frontendcolumnname),
                companyname_menu: toText(rd2.companyname_menu),
                companytollfreeno: toText(rd2.companytollfreeno),
                companyname_footer: toText(rd2.companyname_footer),
                isb2cstockitem: toInt(rd2.isb2cstockitem),
                isb2cstorefirstlinkactive: toInt(rd2.isb2cstorefirstlinkactive),
                isdelete: toInt(rd2.isdelete),
                deletedate: toText(rd2.deletedate),
                appuserid: toText(rd2.appuserid),
                ipaddress: toText(rd2.ipaddress),
                IsCustomizeCart: toInt(rd2.IsCustomizeCart),
                IsShowPrice: toInt(rd2.IsShowPrice),
                FrontEndTitle: toText(rd2.FrontEndTitle),
                mobiledomainpath: toText(rd2.mobiledomainpath),
                ipaddomainpath: toText(rd2.ipaddomainpath),
                isShowBrand: toInt(rd2.isShowBrand),
                isShowDesignWiseOrders: toInt(rd2.isShowDesignWiseOrders),
                IsShow_Ecat_Sets: toInt(rd2.IsShow_Ecat_Sets),
                tollfreelabel: toText(rd2.tollfreelabel),
                IsMyPolicy: toInt(rd2.IsMyPolicy),
                IsShowPromotionAlert: toInt(rd2.IsShowPromotionAlert),
                PromotionAlert_Imagename: toText(rd2.PromotionAlert_Imagename),
                MainBanner1_Imagename: toText(rd2.MainBanner1_Imagename),
                MainBanner2_Imagename: toText(rd2.MainBanner2_Imagename),
                MainBanner3_Imagename: toText(rd2.MainBanner3_Imagename),
                MainBanner4_Imagename: toText(rd2.MainBanner4_Imagename),
                MainBanner5_Imagename: toText(rd2.MainBanner5_Imagename),
                MainBanner6_Imagename: toText(rd2.MainBanner6_Imagename),
                MainBanner7_Imagename: toText(rd2.MainBanner7_Imagename),
                MainBanner8_Imagename: toText(rd2.MainBanner8_Imagename),
                MainBanner9_Imagename: toText(rd2.MainBanner9_Imagename),
                MainBanner10_Imagename: toText(rd2.MainBanner10_Imagename),
                SubBanner1_Imagename: toText(rd2.SubBanner1_Imagename),
                SubBanner2_Imagename: toText(rd2.SubBanner2_Imagename),
                SubBanner3_Imagename: toText(rd2.SubBanner3_Imagename),
                MobileBanner1_Imagename: toText(rd2.MobileBanner1_Imagename),
                MobileBanner2_Imagename: toText(rd2.MobileBanner2_Imagename),
                MobileBanner3_Imagename: toText(rd2.MobileBanner3_Imagename),
                MobileBanner4_Imagename: toText(rd2.MobileBanner4_Imagename),
                MobileBanner5_Imagename: toText(rd2.MobileBanner5_Imagename),
                MobileBanner6_Imagename: toText(rd2.MobileBanner6_Imagename),
                MobileBanner7_Imagename: toText(rd2.MobileBanner7_Imagename),
                MobileBanner8_Imagename: toText(rd2.MobileBanner8_Imagename),
                MobileBanner9_Imagename: toText(rd2.MobileBanner9_Imagename),
                MobileBanner10_Imagename: toText(rd2.MobileBanner10_Imagename),
                IsB2CCustomer: toInt(rd2.IsB2CCustomer),
                IsB2CCustomerMobile: toInt(rd2.IsB2CCustomerMobile),
                paytmReturnstr: toText(rd2.paytmReturnstr),
                FrontEndFullName: toText(rd2.FrontEndFullName),
                FrontEndAddress: toText(rd2.FrontEndAddress),
                FrontEndCity: toText(rd2.FrontEndCity),
                FrontEndState: toText(rd2.FrontEndState),
                FrontEndZipCode: toText(rd2.FrontEndZipCode),
                FrontEndContactno1: toText(rd2.FrontEndContactno1),
                FrontEndContactno2: toText(rd2.FrontEndContactno2),
                FrontEndEmail1: toText(rd2.FrontEndEmail1),
                FrontEndEmail2: toText(rd2.FrontEndEmail2),
                FrontEndWebsite: toText(rd2.FrontEndWebsite),
                IsShowPoweredBy: toInt(rd2.IsShowPoweredBy),
                footer_title1: toText(rd2.footer_title1),
                footer_titlelink1: toText(rd2.footer_titlelink1),
                footer_title1detail1: toText(rd2.footer_title1detail1),
                footer_title1detail2: toText(rd2.footer_title1detail2),
                footer_title1detail3: toText(rd2.footer_title1detail3),
                footer_title1detail4: toText(rd2.footer_title1detail4),
                footer_title1detail5: toText(rd2.footer_title1detail5),
                footer_title1detail6: toText(rd2.footer_title1detail6),
                footer_title1detail7: toText(rd2.footer_title1detail7),
                footer_title1detaillink1: toText(rd2.footer_title1detaillink1),
                footer_title1detaillink2: toText(rd2.footer_title1detaillink2),
                footer_title1detaillink3: toText(rd2.footer_title1detaillink3),
                footer_title1detaillink4: toText(rd2.footer_title1detaillink4),
                footer_title1detaillink5: toText(rd2.footer_title1detaillink5),
                footer_title1detaillink6: toText(rd2.footer_title1detaillink6),
                footer_title1detaillink7: toText(rd2.footer_title1detaillink7),
                footer_title2: toText(rd2.footer_title2),
                footer_titlelink2: toText(rd2.footer_titlelink2),
                footer_title2detail1: toText(rd2.footer_title2detail1),
                footer_title2detail2: toText(rd2.footer_title2detail2),
                footer_title2detail3: toText(rd2.footer_title2detail3),
                footer_title2detail4: toText(rd2.footer_title2detail4),
                footer_title2detail5: toText(rd2.footer_title2detail5),
                footer_title2detail6: toText(rd2.footer_title2detail6),
                footer_title2detail7: toText(rd2.footer_title2detail7),
                footer_title2detaillink1: toText(rd2.footer_title2detaillink1),
                footer_title2detaillink2: toText(rd2.footer_title2detaillink2),
                footer_title2detaillink3: toText(rd2.footer_title2detaillink3),
                footer_title2detaillink4: toText(rd2.footer_title2detaillink4),
                footer_title2detaillink5: toText(rd2.footer_title2detaillink5),
                footer_title2detaillink6: toText(rd2.footer_title2detaillink6),
                footer_title2detaillink7: toText(rd2.footer_title2detaillink7),
                footer_title3: toText(rd2.footer_title3),
                footer_titlelink3: toText(rd2.footer_titlelink3),
                footer_title4: toText(rd2.footer_title4),
                footer_titlelink4: toText(rd2.footer_titlelink4),
                footertitle4icon_path1: toText(rd2.footertitle4icon_path1),
                footertitle4icon_path2: toText(rd2.footertitle4icon_path2),
                footertitle4icon_path3: toText(rd2.footertitle4icon_path3),
                footertitle4icon_path4: toText(rd2.footertitle4icon_path4),
                footertitle4icon_path5: toText(rd2.footertitle4icon_path5),
                footertitle4icon_path6: toText(rd2.footertitle4icon_path6),
                footertitle4icon_path7: toText(rd2.footertitle4icon_path7),
                footertitle4icon_path8: toText(rd2.footertitle4icon_path8),
                footertitle4icon_link1: toText(rd2.footertitle4icon_link1),
                footertitle4icon_link2: toText(rd2.footertitle4icon_link2),
                footertitle4icon_link3: toText(rd2.footertitle4icon_link3),
                footertitle4icon_link4: toText(rd2.footertitle4icon_link4),
                footertitle4icon_link5: toText(rd2.footertitle4icon_link5),
                footertitle4icon_link6: toText(rd2.footertitle4icon_link6),
                footertitle4icon_link7: toText(rd2.footertitle4icon_link7),
                footertitle4icon_link8: toText(rd2.footertitle4icon_link8),
                footertitle4icon_tooltip1: toText(rd2.footertitle4icon_tooltip1),
                footertitle4icon_tooltip2: toText(rd2.footertitle4icon_tooltip2),
                footertitle4icon_tooltip3: toText(rd2.footertitle4icon_tooltip3),
                footertitle4icon_tooltip4: toText(rd2.footertitle4icon_tooltip4),
                footertitle4icon_tooltip5: toText(rd2.footertitle4icon_tooltip5),
                footertitle4icon_tooltip6: toText(rd2.footertitle4icon_tooltip6),
                footertitle4icon_tooltip7: toText(rd2.footertitle4icon_tooltip7),
                footertitle4icon_tooltip8: toText(rd2.footertitle4icon_tooltip8),
                groupid: toText(rd2.groupid),
                officeid: toText(rd2.officeid),
                filter_title1: toText(rd2.filter_title1),
                filter_Updatemenu1: toText(rd2.filter_Updatemenu1),
                isfilter_title1: toInt(rd2.isfilter_title1),
                filter_title2: toText(rd2.filter_title2),
                filter_Updatemenu2: toText(rd2.filter_Updatemenu2),
                isfilter_title2: toInt(rd2.isfilter_title2),
                filter_title3: toText(rd2.filter_title3),
                filter_Updatemenu3: toText(rd2.filter_Updatemenu3),
                isfilter_title3: toInt(rd2.isfilter_title3),
                filter_title4: toText(rd2.filter_title4),
                filter_Updatemenu4: toText(rd2.filter_Updatemenu4),
                isfilter_title4: toInt(rd2.isfilter_title4),
                filter_title5: toText(rd2.filter_title5),
                filter_Updatemenu5: toText(rd2.filter_Updatemenu5),
                isfilter_title5: toInt(rd2.isfilter_title5),
                filter_title6: toText(rd2.filter_title6),
                filter_Updatemenu6: toText(rd2.filter_Updatemenu6),
                isfilter_title6: toInt(rd2.isfilter_title6),
                filter_title7: toText(rd2.filter_title7),
                filter_Updatemenu7: toText(rd2.filter_Updatemenu7),
                isfilter_title7: toInt(rd2.isfilter_title7),
                filter_title8: toText(rd2.filter_title8),
                filter_Updatemenu8: toText(rd2.filter_Updatemenu8),
                isfilter_title8: toInt(rd2.isfilter_title8),
                filter_title9: toText(rd2.filter_title9),
                filter_Updatemenu9: toText(rd2.filter_Updatemenu9),
                isfilter_title9: toInt(rd2.isfilter_title9),
                filter_title10: toText(rd2.filter_title10),
                filter_Updatemenu10: toText(rd2.filter_Updatemenu10),
                isfilter_title10: toInt(rd2.isfilter_title10),
                filter_title11: toText(rd2.filter_title11),
                filter_Updatemenu11: toText(rd2.filter_Updatemenu11),
                isfilter_title11: toInt(rd2.isfilter_title11),
                filter_title12: toText(rd2.filter_title12),
                filter_Updatemenu12: toText(rd2.filter_Updatemenu12),
                isfilter_title12: toInt(rd2.isfilter_title12),
                filter_title13: toText(rd2.filter_title13),
                filter_Updatemenu13: toText(rd2.filter_Updatemenu13),
                isfilter_title13: toInt(rd2.isfilter_title13),
                filter_title14: toText(rd2.filter_title14),
                filter_Updatemenu14: toText(rd2.filter_Updatemenu14),
                isfilter_title14: toInt(rd2.isfilter_title14),
                filter_title15: toText(rd2.filter_title15),
                filter_Updatemenu15: toText(rd2.filter_Updatemenu15),
                isfilter_title15: toInt(rd2.isfilter_title15),
                filter_title16: toText(rd2.filter_title16),
                filter_Updatemenu16: toText(rd2.filter_Updatemenu16),
                isfilter_title16: toInt(rd2.isfilter_title16),
                filter_title17: toText(rd2.filter_title17),
                filter_Updatemenu17: toText(rd2.filter_Updatemenu17),
                isfilter_title17: toInt(rd2.isfilter_title17),
                filter_title18: toText(rd2.filter_title18),
                filter_Updatemenu18: toText(rd2.filter_Updatemenu18),
                isfilter_title18: toInt(rd2.isfilter_title18),
                dynamic_menu1: toText(rd2.dynamic_menu1),
                dynamic_menuupdate1: toText(rd2.dynamic_menuupdate1),
                isdynamic_menu1: toInt(rd2.isdynamic_menu1),
                dynamic_menu2: toText(rd2.dynamic_menu2),
                dynamic_menuupdate2: toText(rd2.dynamic_menuupdate2),
                isdynamic_menu2: toInt(rd2.isdynamic_menu2),
                dynamic_menu3: toText(rd2.dynamic_menu3),
                dynamic_menuupdate3: toText(rd2.dynamic_menuupdate3),
                isdynamic_menu3: toInt(rd2.isdynamic_menu3),
                dynamic_menu4: toText(rd2.dynamic_menu4),
                dynamic_menuupdate4: toText(rd2.dynamic_menuupdate4),
                isdynamic_menu4: toInt(rd2.isdynamic_menu4),
                dynamic_menu5: toText(rd2.dynamic_menu5),
                dynamic_menuupdate5: toText(rd2.dynamic_menuupdate5),
                isdynamic_menu5: toInt(rd2.isdynamic_menu5),
                dynamic_menu6: toText(rd2.dynamic_menu6),
                dynamic_menuupdate6: toText(rd2.dynamic_menuupdate6),
                isdynamic_menu6: toInt(rd2.isdynamic_menu6),
                dynamic_menu7: toText(rd2.dynamic_menu7),
                dynamic_menuupdate7: toText(rd2.dynamic_menuupdate7),
                isdynamic_menu7: toInt(rd2.isdynamic_menu7),
                dynamic_menu8: toText(rd2.dynamic_menu8),
                dynamic_menuupdate8: toText(rd2.dynamic_menuupdate8),
                isdynamic_menu8: toInt(rd2.isdynamic_menu8),
                jewellery_menu_level1: toText(rd2.jewellery_menu_level1),
                jewellery_menu_level2: toText(rd2.jewellery_menu_level2),
                jewellery_menu_level3: toText(rd2.jewellery_menu_level3),
                collection_menu_level1: toText(rd2.collection_menu_level1),
                customize_footer: toText(rd2.customize_footer),
                footer2_title1: toText(rd2.footer2_title1),
                footer2_titlelink1: toText(rd2.footer2_titlelink1),
                isvisiblefooter2_title1: toInt(rd2.isvisiblefooter2_title1),
                footer2_title2: toText(rd2.footer2_title2),
                footer2_titlelink2: toText(rd2.footer2_titlelink2),
                isvisiblefooter2_title2: toInt(rd2.isvisiblefooter2_title2),
                footer2_title3: toText(rd2.footer2_title3),
                footer2_titlelink3: toText(rd2.footer2_titlelink3),
                isvisiblefooter2_title3: toInt(rd2.isvisiblefooter2_title3),
                footer2_title4: toText(rd2.footer2_title4),
                footer2_titlelink4: toText(rd2.footer2_titlelink4),
                isvisiblefooter2_title4: toInt(rd2.isvisiblefooter2_title4),
                footer2_title5: toText(rd2.footer2_title5),
                footer2_titlelink5: toText(rd2.footer2_titlelink5),
                isvisiblefooter2_title5: toInt(rd2.isvisiblefooter2_title5),
                footer2_title6: toText(rd2.footer2_title6),
                footer2_titlelink6: toText(rd2.footer2_titlelink6),
                isvisiblefooter2_title6: toInt(rd2.isvisiblefooter2_title6),
                footer2_title7: toText(rd2.footer2_title7),
                footer2_titlelink7: toText(rd2.footer2_titlelink7),
                isvisiblefooter2_title7: toInt(rd2.isvisiblefooter2_title7),
                footer2_title8: toText(rd2.footer2_title8),
                footer2_titlelink8: toText(rd2.footer2_titlelink8),
                isvisiblefooter2_title8: toInt(rd2.isvisiblefooter2_title8),
                footer2_title9: toText(rd2.footer2_title9),
                footer2_titlelink9: toText(rd2.footer2_titlelink9),
                isvisiblefooter2_title9: toInt(rd2.isvisiblefooter2_title9),
                footer2_title10: toText(rd2.footer2_title10),
                footer2_titlelink10: toText(rd2.footer2_titlelink10),
                isvisiblefooter2_title10: toInt(rd2.isvisiblefooter2_title10),
                footer2_title11: toText(rd2.footer2_title11),
                footer2_titlelink11: toText(rd2.footer2_titlelink11),
                isvisiblefooter2_title11: toInt(rd2.isvisiblefooter2_title11),
                footer2_title12: toText(rd2.footer2_title12),
                footer2_titlelink12: toText(rd2.footer2_titlelink12),
                isvisiblefooter2_title12: toInt(rd2.isvisiblefooter2_title12),
                footer2_title13: toText(rd2.footer2_title13),
                footer2_titlelink13: toText(rd2.footer2_titlelink13),
                isvisiblefooter2_title13: toInt(rd2.isvisiblefooter2_title13),
                footer2_title14: toText(rd2.footer2_title14),
                footer2_titlelink14: toText(rd2.footer2_titlelink14),
                isvisiblefooter2_title14: toInt(rd2.isvisiblefooter2_title14),
                footer2_title15: toText(rd2.footer2_title15),
                footer2_titlelink15: toText(rd2.footer2_titlelink15),
                isvisiblefooter2_title15: toInt(rd2.isvisiblefooter2_title15),
                frontendhomepath: toText(rd2.frontendhomepath),
                IsB2C: toInt(rd2.IsB2C),
                DefaultBanner_Imagename: toText(rd2.DefaultBanner_Imagename),
                CertificateBanner_Imagename: toText(rd2.CertificateBanner_Imagename),
                IsMobileGenderHome: toInt(rd2.IsMobileGenderHome),
                IsNewArrival: toInt(rd2.IsNewArrival),
                CART_SIDE_BANNER_Imagename: toText(rd2.CART_SIDE_BANNER_Imagename),
                diamondstoredomainpath: toText(rd2.diamondstoredomainpath),
                MobileHomePage_Imagename: toText(rd2.MobileHomePage_Imagename),
                loginpage_Imagename: toText(rd2.loginpage_Imagename),
                IsCartPrice: toInt(rd2.IsCartPrice),
                bgImage: toText(rd2.bgImage),
                parallax_Imagename: toText(rd2.parallax_Imagename),
                transparent_Imagename: toText(rd2.transparent_Imagename),
                store_domainname: toText(rd2.store_domainname),
                uKey: toText(rd2.uKey),
                gdpr: toInt(rd2.gdpr),
                IsDirectOrder: toInt(rd2.IsDirectOrder),
                IsShowQuotation: toInt(rd2.IsShowQuotation),
                IsB2Bwishlist: toInt(rd2.IsB2Bwishlist),
                IsWhatsappShare: toInt(rd2.IsWhatsappShare),
                SocialLinkObj: socialLinkStr,
                theme: toText(rd2.theme),
                VisitorId: toInt(rd2.VisitorId)
            });
        }
    });

    transaction();

    // Checkpoint WAL so external tools & database clients immediately see updated rows
    try {
        db.pragma("wal_checkpoint(PASSIVE)");
    } catch (_) {}

    const elapsedMs = Math.round((performance.now() - startTime) * 100) / 100;
    return {
        success: true,
        count: {
            rd: Object.keys(rd).length > 0 ? 1 : 0,
            rd1: rd1.length,
            rd2: Object.keys(rd2).length > 0 ? 1 : 0
        },
        elapsedMs
    };
}
