/**
 * Table Schema: companyinfo
 * Company Information & Store Front-End Settings (rd2[0] / rd2)
 */
export const COMPANY_INFO_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS companyinfo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    registrationno TEXT UNIQUE,
    projectlogolibpath TEXT,
    frontenddomainpath TEXT,
    frontendcolumnname TEXT,
    companyname_menu TEXT,
    companytollfreeno TEXT,
    companyname_footer TEXT,
    isb2cstockitem INTEGER DEFAULT 0,
    isb2cstorefirstlinkactive INTEGER DEFAULT 0,
    isdelete INTEGER DEFAULT 0,
    deletedate TEXT,
    appuserid TEXT,
    ipaddress TEXT,
    IsCustomizeCart INTEGER DEFAULT 0,
    IsShowPrice INTEGER DEFAULT 0,
    FrontEndTitle TEXT,
    mobiledomainpath TEXT,
    ipaddomainpath TEXT,
    isShowBrand INTEGER DEFAULT 0,
    isShowDesignWiseOrders INTEGER DEFAULT 0,
    IsShow_Ecat_Sets INTEGER DEFAULT 0,
    tollfreelabel TEXT,
    IsMyPolicy INTEGER DEFAULT 0,
    IsShowPromotionAlert INTEGER DEFAULT 0,
    PromotionAlert_Imagename TEXT,
    MainBanner1_Imagename TEXT,
    MainBanner2_Imagename TEXT,
    MainBanner3_Imagename TEXT,
    MainBanner4_Imagename TEXT,
    MainBanner5_Imagename TEXT,
    MainBanner6_Imagename TEXT,
    MainBanner7_Imagename TEXT,
    MainBanner8_Imagename TEXT,
    MainBanner9_Imagename TEXT,
    MainBanner10_Imagename TEXT,
    SubBanner1_Imagename TEXT,
    SubBanner2_Imagename TEXT,
    SubBanner3_Imagename TEXT,
    MobileBanner1_Imagename TEXT,
    MobileBanner2_Imagename TEXT,
    MobileBanner3_Imagename TEXT,
    MobileBanner4_Imagename TEXT,
    MobileBanner5_Imagename TEXT,
    MobileBanner6_Imagename TEXT,
    MobileBanner7_Imagename TEXT,
    MobileBanner8_Imagename TEXT,
    MobileBanner9_Imagename TEXT,
    MobileBanner10_Imagename TEXT,
    IsB2CCustomer INTEGER DEFAULT 0,
    IsB2CCustomerMobile INTEGER DEFAULT 0,
    paytmReturnstr TEXT,
    FrontEndFullName TEXT,
    FrontEndAddress TEXT,
    FrontEndCity TEXT,
    FrontEndState TEXT,
    FrontEndZipCode TEXT,
    FrontEndContactno1 TEXT,
    FrontEndContactno2 TEXT,
    FrontEndEmail1 TEXT,
    FrontEndEmail2 TEXT,
    FrontEndWebsite TEXT,
    IsShowPoweredBy INTEGER DEFAULT 0,
    footer_title1 TEXT,
    footer_titlelink1 TEXT,
    footer_title1detail1 TEXT,
    footer_title1detail2 TEXT,
    footer_title1detail3 TEXT,
    footer_title1detail4 TEXT,
    footer_title1detail5 TEXT,
    footer_title1detail6 TEXT,
    footer_title1detail7 TEXT,
    footer_title1detaillink1 TEXT,
    footer_title1detaillink2 TEXT,
    footer_title1detaillink3 TEXT,
    footer_title1detaillink4 TEXT,
    footer_title1detaillink5 TEXT,
    footer_title1detaillink6 TEXT,
    footer_title1detaillink7 TEXT,
    footer_title2 TEXT,
    footer_titlelink2 TEXT,
    footer_title2detail1 TEXT,
    footer_title2detail2 TEXT,
    footer_title2detail3 TEXT,
    footer_title2detail4 TEXT,
    footer_title2detail5 TEXT,
    footer_title2detail6 TEXT,
    footer_title2detail7 TEXT,
    footer_title2detaillink1 TEXT,
    footer_title2detaillink2 TEXT,
    footer_title2detaillink3 TEXT,
    footer_title2detaillink4 TEXT,
    footer_title2detaillink5 TEXT,
    footer_title2detaillink6 TEXT,
    footer_title2detaillink7 TEXT,
    footer_title3 TEXT,
    footer_titlelink3 TEXT,
    footer_title4 TEXT,
    footer_titlelink4 TEXT,
    footertitle4icon_path1 TEXT,
    footertitle4icon_path2 TEXT,
    footertitle4icon_path3 TEXT,
    footertitle4icon_path4 TEXT,
    footertitle4icon_path5 TEXT,
    footertitle4icon_path6 TEXT,
    footertitle4icon_path7 TEXT,
    footertitle4icon_path8 TEXT,
    footertitle4icon_link1 TEXT,
    footertitle4icon_link2 TEXT,
    footertitle4icon_link3 TEXT,
    footertitle4icon_link4 TEXT,
    footertitle4icon_link5 TEXT,
    footertitle4icon_link6 TEXT,
    footertitle4icon_link7 TEXT,
    footertitle4icon_link8 TEXT,
    footertitle4icon_tooltip1 TEXT,
    footertitle4icon_tooltip2 TEXT,
    footertitle4icon_tooltip3 TEXT,
    footertitle4icon_tooltip4 TEXT,
    footertitle4icon_tooltip5 TEXT,
    footertitle4icon_tooltip6 TEXT,
    footertitle4icon_tooltip7 TEXT,
    footertitle4icon_tooltip8 TEXT,
    groupid TEXT,
    officeid TEXT,
    filter_title1 TEXT,
    filter_Updatemenu1 TEXT,
    isfilter_title1 INTEGER DEFAULT 0,
    filter_title2 TEXT,
    filter_Updatemenu2 TEXT,
    isfilter_title2 INTEGER DEFAULT 0,
    filter_title3 TEXT,
    filter_Updatemenu3 TEXT,
    isfilter_title3 INTEGER DEFAULT 0,
    filter_title4 TEXT,
    filter_Updatemenu4 TEXT,
    isfilter_title4 INTEGER DEFAULT 0,
    filter_title5 TEXT,
    filter_Updatemenu5 TEXT,
    isfilter_title5 INTEGER DEFAULT 0,
    filter_title6 TEXT,
    filter_Updatemenu6 TEXT,
    isfilter_title6 INTEGER DEFAULT 0,
    filter_title7 TEXT,
    filter_Updatemenu7 TEXT,
    isfilter_title7 INTEGER DEFAULT 0,
    filter_title8 TEXT,
    filter_Updatemenu8 TEXT,
    isfilter_title8 INTEGER DEFAULT 0,
    filter_title9 TEXT,
    filter_Updatemenu9 TEXT,
    isfilter_title9 INTEGER DEFAULT 0,
    filter_title10 TEXT,
    filter_Updatemenu10 TEXT,
    isfilter_title10 INTEGER DEFAULT 0,
    filter_title11 TEXT,
    filter_Updatemenu11 TEXT,
    isfilter_title11 INTEGER DEFAULT 0,
    filter_title12 TEXT,
    filter_Updatemenu12 TEXT,
    isfilter_title12 INTEGER DEFAULT 0,
    filter_title13 TEXT,
    filter_Updatemenu13 TEXT,
    isfilter_title13 INTEGER DEFAULT 0,
    filter_title14 TEXT,
    filter_Updatemenu14 TEXT,
    isfilter_title14 INTEGER DEFAULT 0,
    filter_title15 TEXT,
    filter_Updatemenu15 TEXT,
    isfilter_title15 INTEGER DEFAULT 0,
    filter_title16 TEXT,
    filter_Updatemenu16 TEXT,
    isfilter_title16 INTEGER DEFAULT 0,
    filter_title17 TEXT,
    filter_Updatemenu17 TEXT,
    isfilter_title17 INTEGER DEFAULT 0,
    filter_title18 TEXT,
    filter_Updatemenu18 TEXT,
    isfilter_title18 INTEGER DEFAULT 0,
    dynamic_menu1 TEXT,
    dynamic_menuupdate1 TEXT,
    isdynamic_menu1 INTEGER DEFAULT 0,
    dynamic_menu2 TEXT,
    dynamic_menuupdate2 TEXT,
    isdynamic_menu2 INTEGER DEFAULT 0,
    dynamic_menu3 TEXT,
    dynamic_menuupdate3 TEXT,
    isdynamic_menu3 INTEGER DEFAULT 0,
    dynamic_menu4 TEXT,
    dynamic_menuupdate4 TEXT,
    isdynamic_menu4 INTEGER DEFAULT 0,
    dynamic_menu5 TEXT,
    dynamic_menuupdate5 TEXT,
    isdynamic_menu5 INTEGER DEFAULT 0,
    dynamic_menu6 TEXT,
    dynamic_menuupdate6 TEXT,
    isdynamic_menu6 INTEGER DEFAULT 0,
    dynamic_menu7 TEXT,
    dynamic_menuupdate7 TEXT,
    isdynamic_menu7 INTEGER DEFAULT 0,
    dynamic_menu8 TEXT,
    dynamic_menuupdate8 TEXT,
    isdynamic_menu8 INTEGER DEFAULT 0,
    jewellery_menu_level1 TEXT,
    jewellery_menu_level2 TEXT,
    jewellery_menu_level3 TEXT,
    collection_menu_level1 TEXT,
    customize_footer TEXT,
    footer2_title1 TEXT,
    footer2_titlelink1 TEXT,
    isvisiblefooter2_title1 INTEGER DEFAULT 0,
    footer2_title2 TEXT,
    footer2_titlelink2 TEXT,
    isvisiblefooter2_title2 INTEGER DEFAULT 0,
    footer2_title3 TEXT,
    footer2_titlelink3 TEXT,
    isvisiblefooter2_title3 INTEGER DEFAULT 0,
    footer2_title4 TEXT,
    footer2_titlelink4 TEXT,
    isvisiblefooter2_title4 INTEGER DEFAULT 0,
    footer2_title5 TEXT,
    footer2_titlelink5 TEXT,
    isvisiblefooter2_title5 INTEGER DEFAULT 0,
    footer2_title6 TEXT,
    footer2_titlelink6 TEXT,
    isvisiblefooter2_title6 INTEGER DEFAULT 0,
    footer2_title7 TEXT,
    footer2_titlelink7 TEXT,
    isvisiblefooter2_title7 INTEGER DEFAULT 0,
    footer2_title8 TEXT,
    footer2_titlelink8 TEXT,
    isvisiblefooter2_title8 INTEGER DEFAULT 0,
    footer2_title9 TEXT,
    footer2_titlelink9 TEXT,
    isvisiblefooter2_title9 INTEGER DEFAULT 0,
    footer2_title10 TEXT,
    footer2_titlelink10 TEXT,
    isvisiblefooter2_title10 INTEGER DEFAULT 0,
    footer2_title11 TEXT,
    footer2_titlelink11 TEXT,
    isvisiblefooter2_title11 INTEGER DEFAULT 0,
    footer2_title12 TEXT,
    footer2_titlelink12 TEXT,
    isvisiblefooter2_title12 INTEGER DEFAULT 0,
    footer2_title13 TEXT,
    footer2_titlelink13 TEXT,
    isvisiblefooter2_title13 INTEGER DEFAULT 0,
    footer2_title14 TEXT,
    footer2_titlelink14 TEXT,
    isvisiblefooter2_title14 INTEGER DEFAULT 0,
    footer2_title15 TEXT,
    footer2_titlelink15 TEXT,
    isvisiblefooter2_title15 INTEGER DEFAULT 0,
    frontendhomepath TEXT,
    IsB2C INTEGER DEFAULT 0,
    DefaultBanner_Imagename TEXT,
    CertificateBanner_Imagename TEXT,
    IsMobileGenderHome INTEGER DEFAULT 0,
    IsNewArrival INTEGER DEFAULT 0,
    CART_SIDE_BANNER_Imagename TEXT,
    diamondstoredomainpath TEXT,
    MobileHomePage_Imagename TEXT,
    loginpage_Imagename TEXT,
    IsCartPrice INTEGER DEFAULT 0,
    bgImage TEXT,
    parallax_Imagename TEXT,
    transparent_Imagename TEXT,
    store_domainname TEXT,
    uKey TEXT,
    gdpr INTEGER DEFAULT 0,
    IsDirectOrder INTEGER DEFAULT 0,
    IsShowQuotation INTEGER DEFAULT 0,
    IsB2Bwishlist INTEGER DEFAULT 0,
    IsWhatsappShare INTEGER DEFAULT 0,
    SocialLinkObj TEXT,
    theme TEXT,
    VisitorId INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_companyinfo_regno ON companyinfo(registrationno);
CREATE INDEX IF NOT EXISTS idx_companyinfo_store_domain ON companyinfo(store_domainname);
`;

export default COMPANY_INFO_TABLE_SQL;
