/**
 * Table Schema: storeinit
 * Core Store Configuration (rd[0] / rd)
 */
export const STORE_INIT_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS storeinit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    YearCode TEXT,
    version TEXT,
    ApiUrl TEXT,
    sv TEXT,
    FrontEnd_RegNo TEXT,
    ukey TEXT,
    domain TEXT UNIQUE,
    ufcc TEXT,
    token TEXT,
    UploadLogicalPath TEXT,
    WebSiteStaticImagePath TEXT,
    Socket_URL TEXT,
    Socket_Address TEXT,
    Socket_Path TEXT,
    ProCatLogbanner TEXT,
    favicon TEXT,
    companyMlogo TEXT,
    companylogo TEXT,
    companyname TEXT,
    companyorderemail TEXT,
    companysupportemail TEXT,
    newslatter TEXT,
    IsB2BWebsite INTEGER DEFAULT 0,
    PolicyApplyOnId INTEGER DEFAULT 0,
    PolicyApplyOnName TEXT,
    IsProductWebCustomization INTEGER DEFAULT 0,
    IsMetalCustomization INTEGER DEFAULT 0,
    IsDiamondCustomization INTEGER DEFAULT 0,
    IsCsCustomization INTEGER DEFAULT 0,
    IsCeilingApply INTEGER DEFAULT 0,
    IsMetalCustComb INTEGER DEFAULT 0,
    IsDiamondCustComb INTEGER DEFAULT 0,
    IsCsCustComb INTEGER DEFAULT 0,
    IsStockWebsite INTEGER DEFAULT 0,
    IsSizeWiseDesignWt INTEGER DEFAULT 0,
    IsEcatDesignset INTEGER DEFAULT 0,
    IsMyaccount INTEGER DEFAULT 0,
    IsDiscount INTEGER DEFAULT 0,
    IsPriceShow INTEGER DEFAULT 0,
    IsPriceBreakUp INTEGER DEFAULT 0,
    IsRoundOff INTEGER DEFAULT 0,
    IsMetalWeight INTEGER DEFAULT 0,
    IsDiamondWeight INTEGER DEFAULT 0,
    IsDiamondPcs INTEGER DEFAULT 0,
    IsStoneWeight INTEGER DEFAULT 0,
    IsStonePcs INTEGER DEFAULT 0,
    IsGrossWeight INTEGER DEFAULT 0,
    IsMetalTypeWithColor INTEGER DEFAULT 0,
    RoundOffval REAL DEFAULT 0,
    IsColorWiseImages INTEGER DEFAULT 0,
    IsProductListPagination INTEGER DEFAULT 0,
    PageSize INTEGER DEFAULT 10,
    DesignImageFolBackEnd TEXT,
    DesignImageFol TEXT,
    CDNDesignImageFol TEXT,
    CDNDesignImageFolThumb TEXT,
    DesignSetImageFol TEXT,
    AlbumImageFol TEXT,
    pricemanagement_pricemastersetid INTEGER DEFAULT 0,
    pricemanagement_laboursetid INTEGER DEFAULT 0,
    SettingPriceUniqueNo INTEGER DEFAULT 0,
    diamondpricelistname TEXT,
    colorstonepricelistname TEXT,
    PackageId INTEGER DEFAULT 0,
    PackageName TEXT,
    cmboDiaQCid TEXT,
    cmboDiaQualityColor TEXT,
    cmboCSQCid TEXT,
    cmboCSQualityColor TEXT,
    MetalId INTEGER DEFAULT 0,
    cmboMetalType TEXT,
    Country TEXT,
    CurrencyCodeid INTEGER DEFAULT 0,
    CurrencyCode TEXT,
    Currencyname TEXT,
    CurrencyRate REAL DEFAULT 1.0,
    Currencysymbol TEXT,
    ImgTh TEXT,
    ImgMe TEXT,
    ImgOr TEXT,
    VPath TEXT,
    CDNVPath TEXT,
    Themeno INTEGER DEFAULT 1,
    Headerno INTEGER DEFAULT 1,
    Blockno INTEGER DEFAULT 1,
    Footerno INTEGER DEFAULT 1,
    IsHomeTrending INTEGER DEFAULT 0,
    IsHomeBestSeller INTEGER DEFAULT 0,
    IsHomeNewArrival INTEGER DEFAULT 0,
    IsHomeDesignSet INTEGER DEFAULT 0,
    IsHomeAlbum INTEGER DEFAULT 0,
    IsProductDetailSimilarDesign INTEGER DEFAULT 0,
    IsProductDetailDesignSet INTEGER DEFAULT 0,
    IsGrossWtFilter INTEGER DEFAULT 0,
    IsMetalWtFilter INTEGER DEFAULT 0,
    IsDiamondWtFilter INTEGER DEFAULT 0,
    IsStoneWtFilter INTEGER DEFAULT 0,
    DomainForNo INTEGER DEFAULT 0,
    DomainFor TEXT,
    IsPLW INTEGER DEFAULT 0,
    BrowserTitle TEXT,
    IsDesignSetInMenu INTEGER DEFAULT 0,
    DesignSetInMenu TEXT,
    IsVision360 INTEGER DEFAULT 0,
    Vision360URL TEXT,
    IsMakeToOrderBatch INTEGER DEFAULT 0,
    CartNo INTEGER DEFAULT 1,
    IsTaxIncludePrice INTEGER DEFAULT 0,
    FileCreateDate TEXT,
    CacheRebuildDate TEXT,
    RollOverNo INTEGER DEFAULT 0,
    IsWebMobileLoginOff INTEGER DEFAULT 0,
    IsEcomOtpVerification INTEGER DEFAULT 0,
    IsSolitaireWebsite INTEGER DEFAULT 0,
    IsZeroPriceProductShow INTEGER DEFAULT 0,
    IsSignUpWithCompanyInfo INTEGER DEFAULT 0,
    IsStaticMenu INTEGER DEFAULT 0,
    Website_Email TEXT,
    IsMultiVariantCart INTEGER DEFAULT 0,
    IsRemarkOnProductDetail INTEGER DEFAULT 0,
    IsCustomOrder INTEGER DEFAULT 0,
    IsWhatsappNotification INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_storeinit_domain ON storeinit(domain);
CREATE INDEX IF NOT EXISTS idx_storeinit_token ON storeinit(token);
CREATE INDEX IF NOT EXISTS idx_storeinit_ukey ON storeinit(ukey);
CREATE INDEX IF NOT EXISTS idx_storeinit_regno ON storeinit(FrontEnd_RegNo);
`;

export default STORE_INIT_TABLE_SQL;
