import { getTenantDb, closeTenantDb } from "./tenantManager.js";
import { getDomainsFromThemeMap } from "./initAllDatabases.js";
import { batchInsertDesigns } from "./procedures/batchInsertDesigns.js";

export const
 sampleDesigns =   [{
                "SrNo": "1",
                "id": 3771,
                "DesignId": 3771,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "81-001",
                "designno": "81",
                "autocode": "3807",
                "IsNewArrival": 1,
                "TitleLine": "",
                "DisplayOrder": 220273,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-21T12:34:04.950Z",
                "FrontEnd1_newArrivalsto": "2026-09-30T00:00:00.000Z",
                "IsMrpBase": 0,
                "DiaQuaCol": "IJ,LV,PD",
                "CsQuaCol": "",
                "SoldCnt": 2,
                "Nwt": 9.65,
                "Gwt": 10,
                "Dwt": 1.75,
                "Dpcs": 20,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 113387.5,
                "UnitCostWithMarkUp": 113387.5,
                "UnitCostWithMarkUpIncTax": 113387.5,
                "Metal_Cost": 108562.5,
                "Labour_Cost": 4825,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 33,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "2",
                "id": 3770,
                "DesignId": 3770,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "81-001",
                "designno": "R-001",
                "autocode": "3806",
                "IsNewArrival": 0,
                "TitleLine": "Classic Solitaire Ring",
                "DisplayOrder": 220272,
                "IsInReadyStock": 0,
                "description": "Elegant solitaire ring with a timeless design, perfect for daily wear and special occasions.",
                "EntryDate": "2026-08-17T15:24:28.900Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "SI,IJ",
                "CsQuaCol": "VS1,BLK",
                "SoldCnt": 0,
                "Nwt": 2,
                "Gwt": 3.16,
                "Dwt": 0.4,
                "Dpcs": 2,
                "CSwt": 0.4,
                "CSpcs": 2,
                "UnitCost": 23500,
                "UnitCostWithMarkUp": 23500,
                "UnitCostWithMarkUpIncTax": 23500,
                "Metal_Cost": 22500,
                "Labour_Cost": 1000,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 2,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 4,
                "ColorImageCount": 5,
                "360ImageCount": 0,
                "VideoCount": 1,
                "ImageExtension": "webp",
                "360ImageExtension": "",
                "VideoExtension": "mp4",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "[{\"Nm\":1,\"Ex\":\"mp4\",\"CN\":\"\",\"TI\":3},{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1},{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"Rose Gold\",\"TI\":2},{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"White\",\"TI\":2},{\"Nm\":2,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1},{\"Nm\":2,\"Ex\":\"webp\",\"CN\":\"Rose Gold\",\"TI\":2},{\"Nm\":2,\"Ex\":\"webp\",\"CN\":\"White\",\"TI\":2},{\"Nm\":3,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1},{\"Nm\":3,\"Ex\":\"webp\",\"CN\":\"Rose Gold\",\"TI\":2},{\"Nm\":3,\"Ex\":\"webp\",\"CN\":\"White\",\"TI\":2},{\"Nm\":4,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1},{\"Nm\":4,\"Ex\":\"webp\",\"CN\":\"Rose Gold\",\"TI\":2},{\"Nm\":4,\"Ex\":\"webp\",\"CN\":\"White\",\"TI\":2},{\"Nm\":5,\"Ex\":\"webp\",\"CN\":\"Rose Gold\",\"TI\":2}]"
            },
            {
                "SrNo": "3",
                "id": 3769,
                "DesignId": 3769,
                "IsBestSeller": 0,
                "IsTrending": 1,
                "ArticleNo": "M01-001",
                "designno": "M01",
                "autocode": "3805",
                "IsNewArrival": 0,
                "TitleLine": "Royal Diamod Ring",
                "DisplayOrder": 220271,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T14:20:15.837Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 50,
                "Gwt": 50,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 587500,
                "UnitCostWithMarkUp": 587500,
                "UnitCostWithMarkUpIncTax": 587500,
                "Metal_Cost": 562500,
                "Labour_Cost": 25000,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 15,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 1,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "webp",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "[{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1}]"
            },
            {
                "SrNo": "4",
                "id": 3764,
                "DesignId": 3764,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "MDF001-001",
                "designno": "MDF001",
                "autocode": "3801",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "VVS,WHITE",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 9,
                "Gwt": 10,
                "Dwt": 5,
                "Dpcs": 1,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 105750,
                "UnitCostWithMarkUp": 105750,
                "UnitCostWithMarkUpIncTax": 105750,
                "Metal_Cost": 101250,
                "Labour_Cost": 4500,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 15,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 1,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "webp",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "[{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1}]"
            },
            {
                "SrNo": "5",
                "id": 3765,
                "DesignId": 3765,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "MDX001-001",
                "designno": "MDX001",
                "autocode": "3791",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "VS,JK",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 6.5,
                "Gwt": 6.536,
                "Dwt": 0.18,
                "Dpcs": 17,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 76375,
                "UnitCostWithMarkUp": 76375,
                "UnitCostWithMarkUpIncTax": 76375,
                "Metal_Cost": 73125,
                "Labour_Cost": 3250,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 14,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "6",
                "id": 3766,
                "DesignId": 3766,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "MF001-001",
                "designno": "MF001",
                "autocode": "3802",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 6.2,
                "Gwt": 6.2,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 72850,
                "UnitCostWithMarkUp": 72850,
                "UnitCostWithMarkUpIncTax": 72850,
                "Metal_Cost": 69750,
                "Labour_Cost": 3100,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 14,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "7",
                "id": 3767,
                "DesignId": 3767,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "MX001-001",
                "designno": "MX001",
                "autocode": "3804",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 10.5,
                "Gwt": 10.5,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 123375,
                "UnitCostWithMarkUp": 123375,
                "UnitCostWithMarkUpIncTax": 123375,
                "Metal_Cost": 118125,
                "Labour_Cost": 5250,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 15,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "8",
                "id": 3756,
                "DesignId": 3756,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "F001-001",
                "designno": "F001",
                "autocode": "3796",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 2.4,
                "Gwt": 2.4,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 28200,
                "UnitCostWithMarkUp": 28200,
                "UnitCostWithMarkUpIncTax": 28200,
                "Metal_Cost": 27000,
                "Labour_Cost": 1200,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 14,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "9",
                "id": 3757,
                "DesignId": 3757,
                "IsBestSeller": 0,
                "IsTrending": 0,
                "ArticleNo": "FX001-001",
                "designno": "FX001",
                "autocode": "3803",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 1.6,
                "Gwt": 1.6,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 18800,
                "UnitCostWithMarkUp": 18800,
                "UnitCostWithMarkUpIncTax": 18800,
                "Metal_Cost": 18000,
                "Labour_Cost": 800,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 15,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 0,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 0,
                "ImageExtension": "",
                "360ImageExtension": "",
                "VideoExtension": "",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "0"
            },
            {
                "SrNo": "10",
                "id": 3758,
                "DesignId": 3758,
                "IsBestSeller": 0,
                "IsTrending": 1,
                "ArticleNo": "M001-001",
                "designno": "M001",
                "autocode": "3793",
                "IsNewArrival": 0,
                "TitleLine": "",
                "DisplayOrder": 220270,
                "IsInReadyStock": 0,
                "description": "",
                "EntryDate": "2026-08-12T11:59:45.413Z",
                "FrontEnd1_newArrivalsto": null,
                "IsMrpBase": 0,
                "DiaQuaCol": "",
                "CsQuaCol": "",
                "SoldCnt": 0,
                "Nwt": 50,
                "Gwt": 50,
                "Dwt": 0,
                "Dpcs": 0,
                "CSwt": 0,
                "CSpcs": 0,
                "UnitCost": 587500,
                "UnitCostWithMarkUp": 587500,
                "UnitCostWithMarkUpIncTax": 587500,
                "Metal_Cost": 562500,
                "Labour_Cost": 25000,
                "Diamond_Cost": 0,
                "Diamond_SettingCost": 0,
                "ColorStone_Cost": 0,
                "ColorStone_SettingCost": 0,
                "Misc_Cost": 0,
                "Misc_SettingCost": 0,
                "Other_Cost": 0,
                "SolPrice": 0,
                "MetalPurityid": 2,
                "MetalColorid": 23,
                "MetalTypeid": 1,
                "MetalTypePurity": "GOLD 18K",
                "CartId": 0,
                "IsInWish": 0,
                "IsInCart": 0,
                "ImageCount": 1,
                "ColorImageCount": 0,
                "360ImageCount": 0,
                "VideoCount": 1,
                "ImageExtension": "webp",
                "360ImageExtension": "",
                "VideoExtension": "mp4",
                "IsImageNameWithRandNo": 0,
                "ImageVideoDetail": "[{\"Nm\":1,\"Ex\":\"mp4\",\"CN\":\"\",\"TI\":3},{\"Nm\":1,\"Ex\":\"webp\",\"CN\":\"\",\"TI\":1}]"
            }
        ]

/**
 * Seeds design data into one or all tenant databases
 * @param {string} [targetDomain]
 */
export async function seedAllDatabases(targetDomain) {
    console.log("=================================================");
    console.log("🌱 SQLite Batch Design Seeder");
    console.log("=================================================");

    const themeMap = getDomainsFromThemeMap();
    const domains = targetDomain ? [targetDomain] : Object.keys(themeMap);

    console.log(`📦 Seeding ${sampleDesigns.length} records into ${domains.length} tenant DB(s)...\n`);

    for (const domain of domains) {
        try {
            const db = getTenantDb(domain);
            const res = batchInsertDesigns(db, sampleDesigns);
            console.log(`✅ [${domain}] -> Inserted ${res.insertedCount} designs`);
        } catch (err) {
            console.error(`❌ [${domain}] -> Failed:`, err.message);
        }
    }

    closeTenantDb();
    console.log("\n✨ Batch insertion completed successfully!");
}

// Run if called via CLI
if (process.argv[1] && process.argv[1].endsWith("seedDesigns.js")) {
    const domainArg = process.argv[2];
    seedAllDatabases(domainArg);
}
